import '../../models/event_item.dart';
import '../../models/core_team_member.dart';
import '../../models/announcement_item.dart';

class MockData {
  static final List<EventItem> events = [
    EventItem(
      id: 'caseblitz__26',
      title: 'CaseBlitz \'26',
      category: 'Flagship',
      organizerClub: 'Product Management & 180DC',
      venue: 'NVCTI Incubation & NLHC',
      time: '09:00 AM - 04:00 PM (Overnight)',
      date: 'Oct 8-9, 2026',
      prizePool: '₹ 50,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by Product Management & 180DC at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdSvIrxl8SFP16c3nVU4ZvfCux_QbSUCxSosBAMZMCsHnG_jQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
    EventItem(
      id: 'questree__26',
      title: 'QuesTree \'26',
      category: 'Club',
      organizerClub: 'Fintech Club',
      venue: 'NLHC Hall 1',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A fintech-focused challenge testing financial knowledge, analytical thinking, and decision making.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScsuG3fa9uePrzfe7hOskmV8nzyF4BE7DalZr3sU1EA_dPUjg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'mathalon',
      title: 'Mathalon',
      category: 'Departmental',
      organizerClub: 'MNC Department',
      venue: 'Maths Dept Seminar Hall',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'A mathematics-focused competition designed to test mathematical reasoning and problem-solving skills.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSexODKL1fwQDvSY_Ft4Kxa3VJgFL_0FoZ-iAHvz9gIVMFdjfQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'vibehack__26',
      title: 'VibeHack \'26',
      category: 'Flagship',
      organizerClub: 'CyberLabs WebD',
      venue: 'Computer Center Lab 1',
      time: '10:00 AM - 11:00 AM (Kickoff)',
      date: 'Oct 9, 2026',
      prizePool: '₹ 45,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by CyberLabs WebD at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdP94ZSBPRwn5-yYekEj_SXIjY4AzN7PjC2Pbh9FHyaMbTEMg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
    EventItem(
      id: 'code_the_cosmos',
      title: 'Code The Cosmos',
      category: 'Club',
      organizerClub: 'Astronomy Club (ASTC)',
      venue: 'Penman Auditorium',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'A technical challenge combining coding, computational thinking, and the exploration of space-related concepts.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdNc6uuL9p2V6WqHLenLPcHMVxa3d10A-vjy9m3MWql0UqaTw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'aethera',
      title: 'Aethera',
      category: 'Departmental',
      organizerClub: 'Environmental Dept',
      venue: 'Environmental Science Hall',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'An environmental-themed event exploring ideas and challenges related to the environment.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/AETHERA.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf-5tEtvXaG-3uYM7wlIVuzSVSblic6kzvVEYEgskXgy2i2Dg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'gate_craft',
      title: 'Gate Craft',
      category: 'Club',
      organizerClub: 'Electronics & IoT Club',
      venue: 'VLSI Lab, ECE Dept',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A technical challenge designed around engineering concepts and problem solving.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/GateCraft.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdF5yaVfEX9T-uyzHbxwZYTy5E67mTaWZsqH3ZoXlbPc6cUwA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'aeroglide',
      title: 'AeroGlide',
      category: 'Club',
      organizerClub: 'MechismuS',
      venue: 'SAC Ground Aeromodelling Arena',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'An aerospace-themed technical challenge exploring flight, design, and engineering.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/AeroGlide.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScsUCGj9GfukLoVypdvMPrvMdRtXaV1EW6sN6KxZXR_1zpqaQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'mechismu_overflow',
      title: 'Mechismu Overflow',
      category: 'Club',
      organizerClub: 'MechismuS',
      venue: 'Mechanical Workshop',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by MechismuS at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScuess-D-OA42FgiuMlUIevsy6y2wrZk3KLIDHsfcI8Ap99mw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'archway_arena__26',
      title: 'Archway Arena \'26',
      category: 'Departmental',
      organizerClub: 'Civil Department',
      venue: 'Civil Engineering Lab',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A civil engineering competition focused on creativity, technical understanding, and engineering skills.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfDRiRUnKTfHYyC6PSyZGzLe1cPkmbrXCO1QvZP0fhXMJ2b1A/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'forklift__26',
      title: 'ForkLift \'26',
      category: 'Club',
      organizerClub: 'CyberLabs Blockchain',
      venue: 'NLHC Hall 2',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by CyberLabs Blockchain at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdKkighjJcLM9bNtiTcFv9Iee8Pz9t-j8lM9d9wXV58afTSpw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'quantum_mania',
      title: 'Quantum Mania',
      category: 'Club',
      organizerClub: 'QARC Club',
      venue: 'Physics Seminar Hall',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'A quantum-themed technical challenge exploring concepts of quantum computing and technology.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd-Q9bPvwxkjvj2VHfUsfMON1xGnmSd0LVGMXfgrJBo5BDZzg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'logic_odyssey',
      title: 'Logic Odyssey',
      category: 'Club',
      organizerClub: 'C3 Club',
      venue: 'NLHC Hall 3',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A logical problem-solving challenge designed to test analytical thinking and reasoning.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/logicOdyssey.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSckWsaTB5QKfhzriT0sWN6a5INiZnVTPsU0bNupnC5upwNP6g/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'reservoir_making___iadc',
      title: 'Reservoir Making - IADC',
      category: 'Departmental',
      organizerClub: 'Petroleum Dept / IADC',
      venue: 'Petroleum Dept Complex',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by Petroleum Dept / IADC at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeBTfee9dWp1trn_o-T30CNZ0rEtqt64FjeUD3GfkU0BWrgLg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'algosort',
      title: 'Algosort',
      category: 'Club',
      organizerClub: 'Maths Club',
      venue: 'Computer Center Lab 2',
      time: '06:00 PM - 07:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'A programming and algorithmic challenge focused on computational thinking and problem solving.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfoteNfZ4BIECbXuXuc4dPe6-SI0csKoO5W4Ly-h29b9wcRzA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'tinas__26',
      title: 'TiNAS \'26',
      category: 'Flagship',
      organizerClub: 'CyberLabs Infosec',
      venue: 'NLHC Hall 1',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 40,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by CyberLabs Infosec at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSez_u7IF7h3p0F0Y4fWAKCqy5pjlo9jFpl9p80J9XfLlh7HbQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
    EventItem(
      id: 'sparkathon',
      title: 'Sparkathon',
      category: 'Departmental',
      organizerClub: 'ECE Department',
      venue: 'ECE Seminar Hall',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'A technical innovation challenge encouraging participants to develop creative engineering solutions.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/Saparkthon.jpeg',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeBwamRY0l9qYbZauwxnG6Ir0L8JIesSPLYwnhkuhom5zpUEA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'escape_room',
      title: 'Escape Room',
      category: 'Club',
      organizerClub: 'Maths Club',
      venue: 'SAC Room 4 & 5',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'An interactive challenge where participants solve puzzles, uncover clues, and work together to escape.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSccueiwWC2vu7bAu5mG6nz1qKqTmQuGd20jJpDof9jeIQp8CA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'edge_ai_challenge',
      title: 'Edge AI Challenge',
      category: 'Club',
      organizerClub: 'Electronics & IoT Club',
      venue: 'IoT Research Lab',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'A technical challenge exploring artificial intelligence and intelligent systems at the edge.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/EdgeAi.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdgmnRAb94DDD-h7D3V6ijVmyUYyd6LeVDdIxv2dsH3p97YNQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'mlmte_quiz_club_quiz',
      title: 'MLMTE Quiz Club Quiz',
      category: 'Departmental',
      organizerClub: 'MLMTE / Quiz Club',
      venue: 'Management Hall 1',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by MLMTE / Quiz Club at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdL84QU92qx3bv6GSLQe3-O93Avqj3pkNqQCbWo7sK_5SxOHg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'angd_3d_animation',
      title: 'AnGD 3D Animation',
      category: 'Club',
      organizerClub: 'Animation & Art Society (AnGD)',
      venue: 'Design Studio NLHC',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A creative challenge centred around 3D animation, visual storytelling, and digital design.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeqHA0yttderk7EIO-NjMEsXkRhrIkzIsTGVxtSw3-v_e0llQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'chakravyuh',
      title: 'ChakraVyuh',
      category: 'Club',
      organizerClub: 'RoboISM',
      venue: 'Central Arena Maze Track',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by RoboISM at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfTL9X7sPZNZAnW1BcERs9v72jQXvlr99s4l89U4I8PGdyn0g/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'alchemist',
      title: 'Alchemist',
      category: 'Departmental',
      organizerClub: 'Chemical Department',
      venue: 'Chemical Dept Seminar Hall',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A chemical engineering themed event focused on technical knowledge, creativity, and problem solving.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeGumZlCZfIZok0Mxd9sc_15VpehTrime3uczr2gLQpUKJP_g/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'convcup__26',
      title: 'ConvCup \'26',
      category: 'Flagship',
      organizerClub: 'CyberLabs ML',
      venue: 'Computer Center Lab 3',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 40,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by CyberLabs ML at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSczTGuyBed05pCtxNKc_fovb4Gv2l5QwGw03Aw5drHhwi6gUw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
    EventItem(
      id: 'autonav',
      title: 'AutoNav',
      category: 'Club',
      organizerClub: 'MechismuS',
      venue: 'Robotics Arena Track',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'An automotive technology challenge focused on autonomous navigation and engineering.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdnrR_Y-UnVpABHiIeJhWOZMN0eRJNjB5XVfCWb-C8NJwBmLg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'q_blueprint',
      title: 'Q-Blueprint',
      category: 'Club',
      organizerClub: 'QARC Club',
      venue: 'NLHC Hall 2',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'A quantum-focused challenge centred around innovative ideas, technical thinking, and problem solving.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfxXvIIU3nt3Oph0QYUTYQNwrDCByfp_cvG3naYQWtJ3NgBHQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'equity_auction',
      title: 'Equity Auction',
      category: 'Club',
      organizerClub: 'Fintech Club',
      venue: 'EDC Auditorium',
      time: '06:00 PM - 07:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A finance-based competitive event centred around equity, valuation, and strategic decision making.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe0AuJyah_VonZsZfXG05nHb-lhRYBxA2LGtOb1OZsc8tjAzw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'pixel_perfect__26',
      title: 'Pixel Perfect \'26',
      category: 'Club',
      organizerClub: 'CyberLabs UI/UX',
      venue: 'NLHC Hall 1',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by CyberLabs UI/UX at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf0r-Of_qJipnNzxYWq50Qu_fSUM4Q918Sxt4m3QBlSZlKVSQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'seek_the_civil_geek__26',
      title: 'Seek the Civil Geek \'26',
      category: 'Departmental',
      organizerClub: 'Civil Department',
      venue: 'Civil Engineering Dept',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'A civil engineering themed challenge testing technical knowledge and problem-solving ability.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSezqSyxY_VpUGS_mbQKuLQQ9mQhK3iVJXetde4oXxGluHo2fw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'robowars',
      title: 'RoboWars',
      category: 'Flagship',
      organizerClub: 'RoboISM',
      venue: 'Central Arena (SAC Ground)',
      time: '10:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 80,000',
      teamSize: '1 - 4 Members',
      description:
          'A high-intensity robotic battle where powerful machines equipped with crushers, launchers, and flamethrowers clash for victory.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/robowars.webp',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSecHwG-hds8YQwvYlRvQ9EQfxBxZnNhtHOb8Ia4WEazvAqMyw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
    EventItem(
      id: 'sbt_quiz',
      title: 'SBT Quiz',
      category: 'Club',
      organizerClub: 'Quiz Club',
      venue: 'Penman Auditorium',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by Quiz Club at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScV31qs0QIyILLQL1AU_hwJeusJGzAxTqrRsHBdllDD67URHw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'fault_hunt',
      title: 'Fault Hunt',
      category: 'Departmental',
      organizerClub: 'ECE Department',
      venue: 'VLSI Simulation Lab',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'An electronics-focused challenge centred around identifying and solving technical faults.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/Fault Hunt.jpeg',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeiwkbItv5Nq71q8_zA8TBgJXyhlAip2wzGLRr8OTEnxPQKlQ/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'appsurd__26',
      title: 'AppSurD \'26',
      category: 'Club',
      organizerClub: 'CyberLabs AppD',
      venue: 'Computer Center Lab 1',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description:
          'An app development challenge focused on building creative and innovative mobile applications.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdwWOSJ5E48lebqLnmXchqEbqC_C1DFSGfC6DJHLatm29C8ng/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'code_wars',
      title: 'Code Wars',
      category: 'Club',
      organizerClub: 'C3 Club',
      venue: 'NLHC Hall 2',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'A competitive coding challenge where participants test their programming and problem-solving abilities.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/codewars.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScyVg0RlpWugmEcvoXBjv_IioXpNF52GHYktbs1_uzpGFKDOA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'spe_event',
      title: 'SPE Event',
      category: 'Departmental',
      organizerClub: 'SPE Student Chapter',
      venue: 'Petroleum Dept Complex',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description:
          'A petroleum engineering event centred around industry knowledge, technical concepts, and problem solving.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc9GdmE6XUHWjHZU2Ais_diInsy60TK7825chyPxQ4x0fZ2gA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'autoexpo',
      title: 'AutoExpo',
      category: 'Fun / Special',
      organizerClub: 'MechismuS',
      venue: 'SAC Open Air Ground',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description:
          'An automotive showcase highlighting vehicles, engineering, and automotive innovation.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSctS1LsOcJ1hKPcWviCkS8n0stpTfjkZtSyFjfHnuHk1T7Kyw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'angd_game_jam',
      title: 'AnGD Game Jam',
      category: 'Club',
      organizerClub: 'Animation & Art Society (AnGD)',
      venue: 'Computer Center Lab 4',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description:
          'A game development challenge focused on creativity, design, and interactive experiences.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd6-dGfbYM_G4Ma9yFeEOkp0MGd7uEPJhQua-sB1xScTGpIRg/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: false,
    ),
    EventItem(
      id: 'robo_wars___grand_final',
      title: 'ROBO WARS - GRAND FINAL',
      category: 'Flagship',
      organizerClub: 'RoboISM',
      venue: 'Central Steel Arena (SAC Ground)',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 1,00,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by RoboISM at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSecHwG-hds8YQwvYlRvQ9EQfxBxZnNhtHOb8Ia4WEazvAqMyw/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
    EventItem(
      id: 'code_ism',
      title: 'CODE ISM',
      category: 'Flagship',
      organizerClub: 'CyberLabs',
      venue: 'Online & Computer Center',
      time: '06:00 PM - 08:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 50,000',
      teamSize: '1 - 4 Members',
      description:
          'Official competitive technical event organized under Concetto\'26 by CyberLabs at IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfzNuxuCfZGHJPfAnYMjZlNDrrcvgWoYrxn1tslZjdhB7s2TA/viewform',
      coordinatorName: 'Concetto Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      isFlagship: true,
    ),
  ];

  static final List<CoreTeamMember> team = [
    CoreTeamMember(
      name: 'Prof. Vasanta Govind Kumar Villuri',
      role: 'Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 326 223 5400',
      email: 'vasanta@iitism.ac.in',
      imageUrl: 'assets/about/convener.png',
      year: 'Faculty Convenor',
      quote: 'It gives immense pleasure to welcome you to CONCETTO 2026, the techno-management festival of IIT (ISM) Dhanbad, as we celebrate the institution’s remarkable centenary journey.',
      order: 1,
    ),
    CoreTeamMember(
      name: 'Prof. Niptika Jana',
      role: 'Co-Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 326 223 5401',
      email: 'niptika@iitism.ac.in',
      imageUrl: 'assets/about/co_convener.png',
      year: 'Faculty Co-Convenor',
      quote: 'The future belongs to those who believe in the beauty of their dreams. CONCETTO’26 Centauri Synapse carries forward this century-old spirit.',
      order: 2,
    ),
    CoreTeamMember(
      name: 'Prof. Arun Udai',
      role: '2nd Co-Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 95231 25843',
      email: 'arunudai@iitism.ac.in',
      imageUrl: 'assets/about/prof_arun_udai.png',
      year: 'Mechanical Engineering',
      quote: 'Innovation thrives where dedication meets passion. Welcome to the grandest edition of Concetto.',
      order: 3,
    ),
    CoreTeamMember(
      name: 'Prof. Gopi Krishna Dondapati',
      role: 'Treasurer',
      vertical: 'Faculty Leadership',
      phone: '+91 90003 95922',
      email: 'gopikrishna@iitism.ac.in',
      imageUrl: 'assets/about/prof_gopi_krishna.png',
      year: 'Mining Machinery Engineering',
      quote: 'Supporting students in pushing frontiers of engineering and technological excellence.',
      order: 4,
    ),
    CoreTeamMember(
      name: 'Sourav Dutta',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 87774 59381',
      email: '25dr0207@iitism.ac.in',
      imageUrl: 'assets/about/sourav_dutta.png',
      year: 'Research Scholar',
      quote: 'Guiding the next generation of engineers to dream bigger and build without limits.',
      order: 5,
    ),
    CoreTeamMember(
      name: 'Badal Singh Naik',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 89841 75908',
      email: '25MB0025@iitism.ac.in',
      imageUrl: 'assets/about/badal_singh.png',
      year: 'Management Studies',
      quote: 'Empowering leadership, seamless operations, and unmatched collaborative spirit.',
      order: 6,
    ),
    CoreTeamMember(
      name: 'Rahul Kumar',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 82108 80177',
      email: '23dr0121@iitism.ac.in',
      imageUrl: 'assets/about/rahul_kumar.png',
      year: 'Research Scholar',
      quote: 'Every breakthrough begins with a single curious mind daring to take the challenge.',
      order: 7,
    ),
    CoreTeamMember(
      name: 'Seemala Devi Sri Pranay',
      role: 'Coordinator',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sdsp.jpg',
      year: 'Core Team',
      quote: '',
      order: 8,
    ),
    CoreTeamMember(
      name: 'Adwait Bhor',
      role: 'General Secretary',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sab.jpg',
      year: 'Core Team',
      quote: '',
      order: 9,
    ),
    CoreTeamMember(
      name: 'Jyotiraditya Singh',
      role: 'President, Student\'s Gymkhana',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sjs.jpg',
      year: 'Core Team',
      quote: '',
      order: 10,
    ),
    CoreTeamMember(
      name: 'Mutyala Vinay',
      role: 'Chairperson, Student\'s Gymkhana',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/mutyala_vinay.jpeg',
      year: 'Core Team',
      quote: '',
      order: 11,
    ),
    CoreTeamMember(
      name: 'Parsh J. Chandra',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccparas.jpeg',
      year: 'Core Team',
      quote: '',
      order: 12,
    ),
    CoreTeamMember(
      name: 'Surendra Singh',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccsurendra.jpeg',
      year: 'Core Team',
      quote: '',
      order: 13,
    ),
    CoreTeamMember(
      name: 'Aditya Chauhan',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccaditya.jpeg',
      year: 'Core Team',
      quote: '',
      order: 14,
    ),
    CoreTeamMember(
      name: 'K. Sai Praneeth',
      role: 'Sponsorship Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-ksp.jpg',
      year: 'Core Team',
      quote: '',
      order: 15,
    ),
    CoreTeamMember(
      name: 'Sumit Kumar Bhagat',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-skb.jpg',
      year: 'Core Team',
      quote: '',
      order: 16,
    ),
    CoreTeamMember(
      name: 'Adi Nath Bhawani',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-anb.jpg',
      year: 'Core Team',
      quote: '',
      order: 17,
    ),
    CoreTeamMember(
      name: 'Kushal Kishore',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-kk.jpg',
      year: 'Core Team',
      quote: '',
      order: 18,
    ),
    CoreTeamMember(
      name: 'Manas Gupta',
      role: 'Event Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-mg.jpg',
      year: 'Core Team',
      quote: '',
      order: 19,
    ),
    CoreTeamMember(
      name: 'Gopisetty Harsha Vardhan Naidu',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-gsr.jpg',
      year: 'Core Team',
      quote: '',
      order: 20,
    ),
    CoreTeamMember(
      name: 'Gurtej Singh',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-gt.jpg',
      year: 'Core Team',
      quote: '',
      order: 21,
    ),
    CoreTeamMember(
      name: 'Shreyashkar Singh',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-ss.jpg',
      year: 'Core Team',
      quote: '',
      order: 22,
    ),
    CoreTeamMember(
      name: 'Medithi Sujith',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-sm.jpg',
      year: 'Core Team',
      quote: '',
      order: 23,
    ),
    CoreTeamMember(
      name: 'Manuwada Adithya',
      role: 'Public Relation Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pr.jpeg',
      year: 'Core Team',
      quote: '',
      order: 24,
    ),
    CoreTeamMember(
      name: 'Shivendu Shekhar',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-ss.jpg',
      year: 'Core Team',
      quote: '',
      order: 25,
    ),
    CoreTeamMember(
      name: 'Apoorv Krishna',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-ak.jpg',
      year: 'Core Team',
      quote: '',
      order: 26,
    ),
    CoreTeamMember(
      name: 'Daksh Mor',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-dm.jpg',
      year: 'Core Team',
      quote: '',
      order: 27,
    ),
    CoreTeamMember(
      name: 'Pidathala Tanmayee',
      role: 'Design Team Head',
      vertical: 'Design',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/des-pt.jpg',
      year: 'Core Team',
      quote: '',
      order: 28,
    ),
    CoreTeamMember(
      name: 'Ramala Vivek',
      role: 'Design Team Co-Head',
      vertical: 'Design',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/des-rv.jpg',
      year: 'Core Team',
      quote: '',
      order: 29,
    ),
    CoreTeamMember(
      name: 'Shivam Verma',
      role: 'Operation And Logistics Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-sv.jpg',
      year: 'Core Team',
      quote: '',
      order: 30,
    ),
    CoreTeamMember(
      name: 'Chandragiri Praveen Kumar Reddy',
      role: 'Operation And Logistics Co-Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-cpkr.jpg',
      year: 'Core Team',
      quote: '',
      order: 31,
    ),
    CoreTeamMember(
      name: 'Siddhant Verma',
      role: 'Operation And Logistics Co-Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-sdv.jpg',
      year: 'Core Team',
      quote: '',
      order: 32,
    ),
    CoreTeamMember(
      name: 'Sucheta Ghosal',
      role: 'Web Development Head',
      vertical: 'Development',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/web-sg.jpg',
      year: 'Core Team',
      quote: '',
      order: 33,
    ),
    CoreTeamMember(
      name: 'Ayilamoni Shivani',
      role: 'App Development Head',
      vertical: 'Development',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/app-as.jpg',
      year: 'Core Team',
      quote: '',
      order: 34,
    ),
    CoreTeamMember(
      name: 'Charan Kondapalli',
      role: 'Security Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-ck.jpg',
      year: 'Core Team',
      quote: '',
      order: 35,
    ),
    CoreTeamMember(
      name: 'K Chaitanya',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-kc1.JPG',
      year: 'Core Team',
      quote: '',
      order: 36,
    ),
    CoreTeamMember(
      name: 'Shipal',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-ship.jpg',
      year: 'Core Team',
      quote: '',
      order: 37,
    ),
    CoreTeamMember(
      name: 'Eslavath Sheshank',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-es.jpg',
      year: 'Core Team',
      quote: '',
      order: 38,
    ),
    CoreTeamMember(
      name: 'Rohit Sunkara',
      role: 'Finance Head',
      vertical: 'Finance',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/fin-r.jpg',
      year: 'Core Team',
      quote: '',
      order: 39,
    ),
    CoreTeamMember(
      name: 'Sunka Varun Vashista',
      role: 'Finance Co-Head',
      vertical: 'Finance',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/fin-v.jpg',
      year: 'Core Team',
      quote: '',
      order: 40,
    ),
    CoreTeamMember(
      name: 'Tanishk Kumar Agrawal',
      role: 'Promotion Head',
      vertical: 'Promotion',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/prom-tka.jpg',
      year: 'Core Team',
      quote: '',
      order: 41,
    ),
    CoreTeamMember(
      name: 'Suyash Pandey',
      role: 'Promotion Co-Head',
      vertical: 'Promotion',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/prom-su.jpg',
      year: 'Core Team',
      quote: '',
      order: 42,
    ),
    CoreTeamMember(
      name: 'Keshav Mehnawat',
      role: 'Marketing Head',
      vertical: 'Marketing',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/keshav2.jpeg',
      year: 'Core Team',
      quote: '',
      order: 43,
    ),
    CoreTeamMember(
      name: 'Snehil Kashyap',
      role: 'Marketing Co-Head',
      vertical: 'Marketing',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/mark-sk.jpg',
      year: 'Core Team',
      quote: '',
      order: 44,
    ),
    CoreTeamMember(
      name: 'Mitta Sai Ramana Siddartha',
      role: 'Hospitality Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-sid.jpg',
      year: 'Core Team',
      quote: '',
      order: 45,
    ),
    CoreTeamMember(
      name: 'M Hema Suharshinii',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-hs.jpg',
      year: 'Core Team',
      quote: '',
      order: 46,
    ),
    CoreTeamMember(
      name: 'Keshav Jha',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-kj.jpg',
      year: 'Core Team',
      quote: '',
      order: 47,
    ),
    CoreTeamMember(
      name: 'Nidhi',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-nidhi.jpg',
      year: 'Core Team',
      quote: '',
      order: 48,
    ),
    CoreTeamMember(
      name: 'Sreeja Peesa',
      role: 'Content And Documentation Head',
      vertical: 'Content And Documentation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/cad-sp.jpg',
      year: 'Core Team',
      quote: '',
      order: 49,
    ),
    CoreTeamMember(
      name: 'Rishabh Shukla',
      role: 'Content And Documentation Co-Head',
      vertical: 'Content And Documentation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/cad-rs.jpg',
      year: 'Core Team',
      quote: '',
      order: 50,
    ),
  ];

  static final List<AnnouncementItem> announcements = [
    AnnouncementItem(
      id: 'ann_1',
      title: "Welcome to CONCETTO '26 — Centenary Edition!",
      description:
          "IIT (ISM) Dhanbad proudly presents Concetto'26 with the theme \"Centauri Synapse — Forged Over a Century, Soaring Towards Infinity\". 39 official competitions and ₹ Lakhs in prizes await!",
      timestamp: DateTime(2026, 10, 1, 10, 0),
      tag: 'FEST',
    ),
    AnnouncementItem(
      id: 'ann_2',
      title: 'RoboWars & ChakraVyuh Arena Registrations Live',
      description:
          'Arena battle slots and maze navigation tracks are now open. Register your bots natively or via verified link before deadlines.',
      timestamp: DateTime(2026, 10, 2, 14, 30),
      tag: 'FLAGSHIP',
    ),
    AnnouncementItem(
      id: 'ann_3',
      title: 'Guest Lecture Series — Industry Leaders',
      description:
          'Special sessions with Indrajit Sanyal (Ericsson), Prasath P (HCLTech), and Varun G (Nokia) at Penman Auditorium on September 25, 2026.',
      timestamp: DateTime(2026, 10, 3, 11, 0),
      tag: 'CDC TALKS',
    ),
    AnnouncementItem(
      id: 'ann_4',
      title: 'MasterStack & PMX180DC CaseBlitz',
      description:
          'Overnight hackathon and premier business case study challenge portals are accepting team registrations.',
      timestamp: DateTime(2026, 10, 3, 18, 0),
      tag: 'HACKATHON',
    ),
    AnnouncementItem(
      id: 'ann_5',
      title: 'Fest Dates & Daily Schedule Confirmed',
      description:
          "Concetto'26 runs from October 08 to October 11, 2026 across IIT (ISM) Dhanbad campus. Access the Schedule tab for timeline and venues!",
      timestamp: DateTime(2026, 10, 4, 9, 0),
      tag: 'SCHEDULE',
    ),
  ];
}
