import '../../models/event_item.dart';
import '../../models/core_team_member.dart';
import '../../models/announcement_item.dart';

class MockData {
  static final List<EventItem> events = [
    EventItem(
      id: 'pmx180dc_caseblitz',
      title: 'CaseBlitz \'26',
      category: 'Flagship',
      organizerClub: 'Product Management & 180DC',
      venue: 'NVCTI Incubation & NLHC Classrooms',
      time: '09:00 AM - 04:00 PM (Overnight)',
      date: 'Oct 8, 2026',
      prizePool: '₹ 50,000',
      teamSize: '1 - 4 Members',
      description: 'Official flagship 24-hour business and product case-solving challenge organized by Product Management Club & 180 Degrees Consulting. Teams analyze real-world market disruption problems and deliver strategic pitches to industry judges.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/Caseblitz.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdSvIrxl8SFP16c3nVU4ZvfCux_QbSUCxSosBAMZMCsHnG_jQ/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/16guxLz779Aa_yiCCO6n68UVMimlZmf4U/view?usp=drive_link',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '+91 98765 43210',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'inauguration_ceremony',
      title: 'Grand Inauguration Ceremony',
      category: 'Stage',
      organizerClub: 'Concetto Advisory & Organizing Committee',
      venue: 'Penman Auditorium',
      time: '05:00 PM - 07:00 PM',
      date: 'Oct 8, 2026',
      prizePool: '',
      teamSize: '',
      description: 'The official grand opening of Concetto\'26 Centenary Edition. Features the arrival of Dignitaries and Chief Guests, the auspicious Lamp Lighting ceremony, and inspiring addresses by Institute Leadership, Director, and Guest of Honour.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Concetto Core Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'concetto_overview_day0',
      title: 'Fest Overview & Centenary Unveiling',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Penman Auditorium',
      time: '07:00 PM - 08:00 PM',
      date: 'Oct 8, 2026',
      prizePool: '',
      teamSize: '',
      description: 'An immersive multimedia journey celebrating 100 years of IIT (ISM) Dhanbad excellence and unveiling the theme \'Centauri Synapse\'. Includes event schedule briefings, theme video launch, and celebration kick-off.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Concetto Media Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'questree__26',
      title: 'QuesTree \'26',
      category: 'Club',
      organizerClub: 'Fintech Club',
      venue: 'NLHC Hall 1',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description: 'High-energy finance and quantitative competition testing market acumen, trading logic, and analytical problem-solving in real-time market scenarios.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScsuG3fa9uePrzfe7hOskmV8nzyF4BE7DalZr3sU1EA_dPUjg/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/13a_zt-jH_XsxDDZ9VsjXCdpaQSmPCMC6p_YKtv3k3l4/edit?usp=sharing',
      coordinatorName: 'Fintech Team',
      coordinatorContact: 'fintech@iitism.ac.in',
      coordinatorEmail: 'fintech@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'mathalon',
      title: 'Mathalon',
      category: 'Departmental',
      organizerClub: 'Society of MnC',
      venue: 'Maths Dept Seminar Hall',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 4 Members',
      description: 'The competition covers topics such as basic logic, probability, geometry, number theory, recurrence relations, basic calculus, and fundamental areas of mathematics, with emphasis on numerical problem-solving rather than lengthy proofs.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSexODKL1fwQDvSY_Ft4Kxa3VJgFL_0FoZ-iAHvz9gIVMFdjfQ/viewform',
      rulebookUrl: '',
      coordinatorName: 'MnC Society',
      coordinatorContact: 'mnc@iitism.ac.in',
      coordinatorEmail: 'mnc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'treasure_hunt_day1',
      title: 'Campus Treasure Hunt Challenge',
      category: 'Fun',
      organizerClub: 'Concetto Event Team',
      venue: 'NLHC & Central Campus Grounds',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 10,000',
      teamSize: '2 - 4 Members',
      description: 'An exhilarating multi-checkpoint race across iconic campus landmarks. Decipher cryptic riddles, solve geo-puzzles, and race against time to unearth the hidden treasure of IIT (ISM).',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Concetto Fun Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'vibehack__26',
      title: 'VibeHack \'26 (DevDash)',
      category: 'Club',
      organizerClub: 'CyberLabs WebD',
      venue: 'NLHC Classrooms',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'DevDash is a fast-paced web development hackathon in which teams receive a surprise challenge and rapidly turn it into a creative, functional and presentable website, promoting creativity, teamwork, problem-solving and practical development skills.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/devdash.jpg',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfp_uUeD5Kekz5Xp2W75PzB6Jt22B-eC176z8R3bM9A86bKmA/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'game_zone_day1',
      title: 'Game Zone — Team Arena Challenges',
      category: 'Fun',
      organizerClub: 'Student Activity Centre (SAC)',
      venue: 'SAC Indoor Arena',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 9, 2026',
      prizePool: 'Exciting Goodies',
      teamSize: 'Open to All',
      description: 'Action-packed mini-games, VR gaming stations, arcade simulators, and LAN multiplayer tournaments open to all fest attendees.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'SAC Games Wing',
      coordinatorContact: 'sac@iitism.ac.in',
      coordinatorEmail: 'sac@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'code_the_cosmos',
      title: 'Code The Cosmos',
      category: 'Club',
      organizerClub: 'ASTC (Astronomy Club)',
      venue: 'NLHC Hall 2',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 4 Members',
      description: 'Computational astrophysics challenge analyzing celestial datasets, planetary orbits, and deep space radio transmissions.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf4Ym6B1f92RkF58sK9v4zW8_Vv8q8c1B5uXp4m6R2Xm7Qk_Q/viewform',
      rulebookUrl: '',
      coordinatorName: 'Hemant',
      coordinatorContact: 'astc@iitism.ac.in',
      coordinatorEmail: 'astc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'aethera',
      title: 'Aethera',
      category: 'Departmental',
      organizerClub: 'Society of Environmental Science & Engg (SESE)',
      venue: 'Department of ESE',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 60,000',
      teamSize: '1 - 3 Members',
      description: 'Aethera is a national sustainability case competition by SESE, IIT (ISM) Dhanbad. Teams of up to 3 tackle a live industry sustainability challenge across three rounds: an online screening test, a case deck submission, and The Boardroom, a live online finale where the top 10 teams pitch before an expert panel and face a surprise Curveball round.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/AETHERA.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc7z8a2C_j7k6B7E1x_V9Yq3K5b2n0m8L1u4P6a9X7c8V1b2Q/viewform',
      rulebookUrl: '',
      coordinatorName: 'SESE Team',
      coordinatorContact: 'sese@iitism.ac.in',
      coordinatorEmail: 'sese@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'gate_craft',
      title: 'Gate Craft',
      category: 'Club',
      organizerClub: 'Electronics & IoT Society',
      venue: 'NLHC Classrooms',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 2 Members',
      description: 'An exciting Minecraft-based technical competition where participants design and build digital logic circuits using Redstone. Participants are challenged to demonstrate logic, creativity, accuracy, and speed within a fixed time.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/GateCraft.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeR6qQ8nB4X9_V5t1Y2u3I4o5P6a7S8d9F0g1H2j3K4l5Z6x7/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/16guxLz779Aa_yiCCO6n68UVMimlZmf4U/view?usp=drive_link',
      coordinatorName: 'Electronics Club',
      coordinatorContact: 'electronics@iitism.ac.in',
      coordinatorEmail: 'electronics@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_1_day1',
      title: 'Keynote Guest Talk 1',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Distinguished lecture by leading visionary technologist and industry pioneer on frontiers of AI, Space Exploration, and the next 100 years of engineering innovation.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Guest Relations Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'aeroglide',
      title: 'AeroGlide (Mechismu)',
      category: 'Club',
      organizerClub: 'Mechismu Aeromodelling',
      venue: 'Lower Ground / Oval Ground',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description: 'Aeromodelling glider design and precision flight showcase. Teams build aerodynamic gliders and compete in flight duration, range, and stabilization trials.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/AeroGlide.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfB8n7m6L5k4J3h2G1f0D9s8A7q6W5e4R3t2Y1u0I9o8P7a6S/viewform',
      rulebookUrl: '',
      coordinatorName: 'Mechismu Lead',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'archway_arena__26',
      title: 'Archway Arena \'26',
      category: 'Departmental',
      organizerClub: 'Civil Engineering Society',
      venue: 'Civil Dept Workshop',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '2 - 4 Members',
      description: 'Structural civil engineering design challenge where teams fabricate load-bearing bridges and arches using sustainable materials and test them to failure under hydraulic load rigs.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd7v6C5b4N3m2Q1w0E9r8T7y6U5i4O3p2A1s0D9f8G7h6J5k4/viewform',
      rulebookUrl: '',
      coordinatorName: 'Civil Society',
      coordinatorContact: 'civil@iitism.ac.in',
      coordinatorEmail: 'civil@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'forklift__26',
      title: 'ForkLift \'26 (Blockchain)',
      category: 'Club',
      organizerClub: 'CyberLabs Blockchain',
      venue: 'NLHC Hall 3',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'Web3 and Smart Contract security competition. Teams audit decentralized protocols, find reentrancy vulnerabilities, and deploy DeFi solutions.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/BlockHunt.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe1r2T3y4U5i6O7p8A9s0D1f2G3h4J5k6L7z8X9c0V1b2N3m4/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'quantum_mania',
      title: 'Quantum Mania',
      category: 'Club',
      organizerClub: 'QARC (Quantum Computing)',
      venue: 'NLHC Hall 4',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 3 Members',
      description: 'Quantum computing algorithm design and simulation hackathon utilizing Qiskit and PennyLane for quantum superposition and entanglement optimization.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf9g8H7j6K5l4Z3x2C1v0B9n8M7a6S5d4F3g2H1j0K9l8Z7x6/viewform',
      rulebookUrl: '',
      coordinatorName: 'QARC Lead',
      coordinatorContact: 'qarc@iitism.ac.in',
      coordinatorEmail: 'qarc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_2_day1',
      title: 'Tech Visionary Guest Talk 2',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Inspirational fireside chat with an entrepreneur and venture leader discussing deep tech startups, scaling engineering breakthroughs, and student innovations.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Guest Relations Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'logic_odyssey',
      title: 'Logic Odyssey',
      category: 'Club',
      organizerClub: 'C3 (Coding Club)',
      venue: 'Computer Center Lab 1',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 3 Members',
      description: 'Competitive programming contest testing dynamic programming, graph traversal, and mathematical algorithmic prowess under severe time constraints.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/logicOdyssey.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc5b4N3m2Q1w0E9r8T7y6U5i4O3p2A1s0D9f8G7h6J5k4L3z2/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1WYPSjvhgbtxNUSOyx0kb6k5dx7_jGywL/edit?usp=sharing&ouid=114871654953852545282&rtpof=true&sd=true',
      coordinatorName: 'Vishal',
      coordinatorContact: 'c3@iitism.ac.in',
      coordinatorEmail: 'c3@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'reservoir_making___iadc',
      title: 'Crack the Crude (IADC)',
      category: 'Departmental',
      organizerClub: 'IADC Student Chapter',
      venue: 'Petroleum Engineering Lab',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 35,000',
      teamSize: '2 - 4 Members',
      description: 'A two-round technical competition designed to test participants\' petroleum engineering knowledge, analytical thinking, and practical skills. Features petroleum-themed identification followed by constructing a functional reservoir model demonstrating porosity, permeability, and fluid migration.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdj3K4l5Z6x7C8v9B0n1M2a3S4d5F6g7H8j9K0l1Z2x3C4v5B/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1pEjSRus_V5Y90rE7zuBkOs1qcw8Yed2v/view?usp=drivesdk',
      coordinatorName: 'IADC Lead',
      coordinatorContact: 'iadc@iitism.ac.in',
      coordinatorEmail: 'iadc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'comedy_night_live',
      title: 'CELEBRITY COMEDY NIGHT',
      category: 'Stage',
      organizerClub: 'Concetto Cultural Wing',
      venue: 'Penman Auditorium / Main Stage',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Get ready for an electrifying evening filled with non-stop laughter and humor! Features a headline standup performance by a leading national comedian. Open entry for all students and delegates carrying valid fest credentials.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Cultural Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'tinas__26',
      title: 'TiNAS \'26 (Infosec CTF)',
      category: 'Club',
      organizerClub: 'CyberLabs Infosec',
      venue: 'Computer Center Lab 2',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'Capture The Flag (CTF) cyber security marathon featuring reverse engineering, binary exploitation, web exploitation, and cryptography forensics.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf0g1H2j3K4l5Z6x7C8v9B0n1M2a3S4d5F6g7H8j9K0l1Z2x3/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'sparkathon',
      title: 'Sparkathon 2.0',
      category: 'Departmental',
      organizerClub: 'Society of Electronics Engineers (SEE)',
      venue: 'NLHC Classrooms',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 40,000',
      teamSize: '2 - 4 Members',
      description: 'Sparkathon is an innovation-oriented technical event encouraging participants to develop creative and practical solutions to real-world engineering problems across embedded electronics, IoT, and signal processing.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/Saparkthon.jpeg',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf4u5I6o7P8a9S0d1F2g3H4j5K6l7Z8x9C0v1B2n3M4a5S6d7/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1XGoeOKbqw8zve-K4h1saq9LQ91wJuWGb/view?usp=drivesdk',
      coordinatorName: 'SEE Team',
      coordinatorContact: 'see@iitism.ac.in',
      coordinatorEmail: 'see@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'minute_to_win_it',
      title: 'Minute to Win It — Fast Reflex Games',
      category: 'Fun',
      organizerClub: 'Concetto Fun Team',
      venue: 'SAC Foyer & Hall',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: 'Fest Goodies',
      teamSize: 'Individual',
      description: 'High-speed 60-second dexterity, coordination, and balancing challenges designed to test participant reflexes and quick thinking under pressure.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Fun Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'escape_room',
      title: 'Escape Room (Maths Club)',
      category: 'Club',
      organizerClub: 'Maths Club',
      venue: 'NLHC Classrooms',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 20,000',
      teamSize: '2 - 4 Members',
      description: 'Immersive logic and puzzle escape game where teams decode lock codes, discover hidden cryptographic keys, and break out within 45 minutes.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe8j9K0l1Z2x3C4v5B6n7M8a9S0d1F2g3H4j5K6l7Z8x9C0v1/viewform',
      rulebookUrl: '',
      coordinatorName: 'Maths Club Lead',
      coordinatorContact: 'mathsclub@iitism.ac.in',
      coordinatorEmail: 'mathsclub@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'edge_ai_challenge',
      title: 'Edge AI Challenge',
      category: 'Club',
      organizerClub: 'Electronics & IoT Society',
      venue: 'NLHC Lab 2',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 3 Members',
      description: 'A team-based technical competition where participants develop, optimize, and deploy a lightweight AI model on resource-constrained embedded hardware judged on accuracy, speed, and efficiency.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/EdgeAi.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe2n3M4a5S6d7F8g9H0j1K2l3Z4x5C6v7B8n9M0a1S2d3F4g5/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1NM1K04y-SFi-x8o9y7VprX2pcn0oeWBO/view?usp=sharing',
      coordinatorName: 'Electronics Club',
      coordinatorContact: 'electronics@iitism.ac.in',
      coordinatorEmail: 'electronics@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'mlmte_quiz_club_quiz',
      title: 'MLMTE National Tech Quiz',
      category: 'Departmental',
      organizerClub: 'Quiz Club',
      venue: 'GJLT Seminar Hall',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'The definitive national technical and science quiz covering metallurgy, material sciences, computing history, space exploration, and engineering trivia.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfp9O8i7U6y5T4r3E2w1Q0z9X8c7V6b5N4m3A2s1D0f9G8h7/viewform',
      rulebookUrl: '',
      coordinatorName: 'Quiz Master',
      coordinatorContact: 'quiz@iitism.ac.in',
      coordinatorEmail: 'quiz@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'hands_on_workshop_day2',
      title: 'Hands-on Tech Workshop',
      category: 'Workshop',
      organizerClub: 'Technical Council',
      venue: 'NLHC Audio-Visual Hall',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Interactive workshop conducted by certified industry professionals covering modern Generative AI pipelines, Embedded Systems, and Autonomous Robotics. Live hands-on coding demonstrations.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Technical Council',
      coordinatorContact: 'tech@iitism.ac.in',
      coordinatorEmail: 'tech@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'angd_3d_animation',
      title: 'Then. Now. Next. (AnGD 3D)',
      category: 'Club',
      organizerClub: 'AnGD (Animation Society)',
      venue: 'Online / Hybrid NLHC',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'A 15-day 3D animation competition where participants bring their creativity to life through 3D modelling, animation, and visual storytelling based on the Centenary theme.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf6j7H8k9L0z1X2c3V4b5N6m7A8s9D0f1G2h3J4k5L6z7X8c9/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1fEXGOvFQEKAH0X7etImMUJirPPyiQFnM/view?usp=drivesdk',
      coordinatorName: 'AnGD Lead',
      coordinatorContact: 'angd@iitism.ac.in',
      coordinatorEmail: 'angd@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_1_day2',
      title: 'Industry Leader Guest Talk 1',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Keynote address by engineering directors and senior researchers discussing industrial automation, semiconductors, and green technology transition.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Guest Relations Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'chakravyuh',
      title: 'ChakraVyuh (RoboISM)',
      category: 'Club',
      organizerClub: 'RoboISM',
      venue: 'Robotics Arena (SAC)',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 40,000',
      teamSize: '2 - 5 Members',
      description: 'Autonomous and manual line follower and obstacle-navigating robotic labyrinth challenge. Bots navigate narrow bridges, elevations, and dynamic gates under strict timing.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd9f8G7h6J5k4L3z2X1c0V9b8N7m6A5s4D3f2G1h0J9k8L7z6/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'roboism@iitism.ac.in',
      coordinatorEmail: 'roboism@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'alchemist',
      title: 'ALCHEMIST',
      category: 'Departmental',
      organizerClub: 'Chemical Engineering Society',
      venue: 'Chemical Dept Lab',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'Chemical process simulation, reaction stoichiometry optimization, and industrial waste heat recovery modeling competition.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe0d1F2g3H4j5K6l7Z8x9C0v1B2n3M4a5S6d7F8g9H0j1K2l3/viewform',
      rulebookUrl: '',
      coordinatorName: 'Chemical Society',
      coordinatorContact: 'chemical@iitism.ac.in',
      coordinatorEmail: 'chemical@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'stunt_show_mechismu',
      title: 'MECHISMU EXTREME BIKE STUNT SHOW',
      category: 'Stage',
      organizerClub: 'Mechismu Automotive Society',
      venue: 'Lower Ground / Open Air Arena',
      time: '02:00 PM - 03:30 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'A heart-stopping, high-octane spectacle! Professional stunt riders deliver precision burnouts, high-angle wheelies, stoppies, drifts, and synchronized motorcycle acrobatics in front of a cheering crowd.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Mechismu Stunt Wing',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'convcup__26',
      title: 'ConvCup \'26 (ML)',
      category: 'Club',
      organizerClub: 'CyberLabs ML',
      venue: 'NLHC Classrooms',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description: 'Kaggle-style Machine Learning and Deep Learning hackathon. Teams train computer vision and LLM models on novel multimodal datasets evaluated on test set F1 scores.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc7z8A9s0D1f2G3h4J5k6L7z8X9c0V1b2N3m4Q5w6E7r8T9y0/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'autonav',
      title: 'AutoNav (Autonomous RC)',
      category: 'Club',
      organizerClub: 'Mechismu',
      venue: 'Mechismu Workshop Arena',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 4 Members',
      description: 'Autonomous vehicle and RC robotics competition featuring computer vision lane tracking, ultrasonic obstacle avoidance, and dynamic speed profiling.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf1g2H3j4K5l6Z7x8C9v0B1n2M3a4S5d6F7g8H9j0K1l2Z3x4/viewform',
      rulebookUrl: '',
      coordinatorName: 'Mechismu Lead',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_2_day2',
      title: 'Innovation Keynote Guest Talk 2',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'A masterclass on deep-sea exploration, autonomous navigation, and the future of mineral exploration in the era of space robotics.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Guest Relations Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'q_blueprint',
      title: 'Q-Blueprint',
      category: 'Club',
      organizerClub: 'QARC (Quantum Club)',
      venue: 'NLHC Hall 1',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 3 Members',
      description: 'Quantum hardware blueprint design and topological error mitigation strategy competition for fault-tolerant quantum computing architectures.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe5r6T7y8U9i0O1p2A3s4D5f6G7h8J9k0L1z2X3c4V5b6N7m8/viewform',
      rulebookUrl: '',
      coordinatorName: 'QARC Lead',
      coordinatorContact: 'qarc@iitism.ac.in',
      coordinatorEmail: 'qarc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'equity_auction',
      title: 'Equity Auction',
      category: 'Club',
      organizerClub: 'Fintech Club',
      venue: 'Online & NLHC',
      time: '06:00 PM - 07:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'Equity Auction is a high-stakes finance-simulation event where teams of 1-4 members take on the role of investors. Participants must navigate market uncertainty, execute strategic negotiations, and react dynamically to sudden market shocks.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd9f8G7h6J5k4L3z2X1c0V9b8N7m6A5s4D3f2G1h0J9k8L7z6/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1REV4cZH4sWdGNWNmw9l6uzvRLYAyS_qIIhY3595iLNE/edit?usp=sharing',
      coordinatorName: 'Fintech Team',
      coordinatorContact: 'fintech@iitism.ac.in',
      coordinatorEmail: 'fintech@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'dj_night_party',
      title: 'MEGA EDM & DJ NIGHT',
      category: 'Stage',
      organizerClub: 'Concetto Cultural Wing',
      venue: 'Main Concert Arena',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Turn up the volume! An immersive audio-visual laser extravaganza featuring world-class DJs, pulsating bass drops, CO2 cannons, and high-energy music. Free entry for all fest pass holders.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Cultural Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'pixel_perfect__26',
      title: 'Pixel Perfect \'26 (UI/UX)',
      category: 'Club',
      organizerClub: 'CyberLabs UI/UX',
      venue: 'NLHC Classrooms',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 3 Members',
      description: 'UI/UX product design sprint. Teams design high-fidelity mobile and web prototypes in Figma focusing on micro-interactions, accessibility, and futuristic design systems.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/design-decode.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf2g3H4j5K6l7Z8x9C0v1B2n3M4a5S6d7F8g9H0j1K2l3Z4x5/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'seek_the_civil_geek__26',
      title: 'Seek the Civil Geek \'26',
      category: 'Departmental',
      organizerClub: 'Civil Engineering Society',
      venue: 'Civil Dept Seminar Hall',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 3 Members',
      description: 'Surveying, soil mechanics, GIS mapping, and smart urban infrastructure planning competition.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe6d7F8g9H0j1K2l3Z4x5C6v7B8n9M0a1S2d3F4g5H6j7K8l9/viewform',
      rulebookUrl: '',
      coordinatorName: 'Civil Society',
      coordinatorContact: 'civil@iitism.ac.in',
      coordinatorEmail: 'civil@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'fun_games_arena',
      title: 'Fun Games Arena & Interactive Booths',
      category: 'Fun',
      organizerClub: 'Concetto Fun Team',
      venue: 'SAC Quadrangle',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: 'Exciting Gifts',
      teamSize: 'Open to All',
      description: 'Carnival stalls, robo-soccer penalty shootout, giant Jenga, laser maze challenges, and tech booth experiences open to all participants and visitors.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Fun Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'robowars',
      title: 'ROBO WARS — Main Elimination Rounds',
      category: 'Flagship',
      organizerClub: 'RoboISM',
      venue: 'RoboWars Armored Arena (SAC Ground)',
      time: '10:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 1,00,000',
      teamSize: '2 - 6 Members',
      description: 'The undisputed colosseum of Concetto! Heavyweight combat robots equipped with drum spinners, flippers, and vertical discs clash in a reinforced polycarbonate cage until destruction or knockout.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/robowars.webp',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf0j1K2l3Z4x5C6v7B8n9M0a1S2d3F4g5H6j7K8l9Z0x1C2v3/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'roboism@iitism.ac.in',
      coordinatorEmail: 'roboism@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'emerging_tech_workshop_day3',
      title: 'Next-Gen AI & Robotics Workshop',
      category: 'Workshop',
      organizerClub: 'Technical Council',
      venue: 'NLHC Audio-Visual Hall',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Deep dive into real-world autonomous systems, ROS 2 robotics stack, and edge neural processing units conducted by visiting engineers.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Tech Council',
      coordinatorContact: 'tech@iitism.ac.in',
      coordinatorEmail: 'tech@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'sbt_quiz',
      title: 'SBT National Quiz',
      category: 'Club',
      organizerClub: 'Quiz Club',
      venue: 'GJLT Seminar Hall',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 3 Members',
      description: 'General science, pop culture, sci-fi and tech trivia quiz conducted by quiz veterans with buzzer rounds and high stakes.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe3c4V5b6N7m8A9s0D1f2G3h4J5k6L7z8X9c0V1b2N3m4Q5w6/viewform',
      rulebookUrl: '',
      coordinatorName: 'Quiz Club Lead',
      coordinatorContact: 'quiz@iitism.ac.in',
      coordinatorEmail: 'quiz@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'fault_hunt',
      title: 'Fault Hunt',
      category: 'Departmental',
      organizerClub: 'Society of Electronics Engineers (SEE)',
      venue: 'Electronics Dept Labs',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 4 Members',
      description: 'Fault Hunt is a circuit-analysis and troubleshooting-based technical event designed to test participants\' understanding of electronic circuits, simulation, debugging, and analytical reasoning through systematic analysis.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/Fault%20Hunt.jpeg',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc7m8A9s0D1f2G3h4J5k6L7z8X9c0V1b2N3m4Q5w6E7r8T9y0/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1erw12jQTDZzvAPLUY6Y8e1QDNbaQHnqh/view?usp=drivesdk',
      coordinatorName: 'SEE Team',
      coordinatorContact: 'see@iitism.ac.in',
      coordinatorEmail: 'see@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'appsurd__26',
      title: 'AppSurD \'26 (Mobile AppD)',
      category: 'Club',
      organizerClub: 'CyberLabs AppD',
      venue: 'Computer Center Lab 1',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'Mobile application development hackathon in Flutter, Android, or React Native building innovative offline-first mobile apps for real problems.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf1g2H3j4K5l6Z7x8C9v0B1n2M3a4S5d6F7g8H9j0K1l2Z3x4/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_1_day3',
      title: 'Futurist Keynote Guest Talk 1',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Keynote on Quantum Advantage, Artificial General Intelligence, and the role of engineering students in transforming Indian deep tech on the global stage.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Guest Relations Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'code_wars',
      title: 'Code Wars',
      category: 'Club',
      organizerClub: 'C3 (Coding Club)',
      venue: 'Computer Center Lab 2',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 3 Members',
      description: 'Head-to-head 1v1 speed coding arena. Solve algorithms, optimize code complexity, and eliminate opponents in rapid-fire knockout rounds.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/codewars.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe5r6T7y8U9i0O1p2A3s4D5f6G7h8J9k0L1z2X3c4V5b6N7m8/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1MdZxBX23qUzihYFlPsadoGJfmWvsVacj/edit?usp=drive_link&ouid=114871654953852545282&rtpof=true&sd=true',
      coordinatorName: 'Vishal',
      coordinatorContact: 'c3@iitism.ac.in',
      coordinatorEmail: 'c3@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'spe_event',
      title: 'Stand Tall - Jack Up Challenge (SPE)',
      category: 'Departmental',
      organizerClub: 'SPE Student Chapter',
      venue: 'Petroleum Department',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 4 Members',
      description: 'Offshore rig design and structural integrity challenge testing stability, ocean current resistance, and drilling capability in offshore basins.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd9f8G7h6J5k4L3z2X1c0V9b8N7m6A5s4D3f2G1h0J9k8L7z6/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1JwM-sddXjfyiTjDHzsaxUMILP-PF7oaTVOOZlWS3Iv0/edit?hl=en&tab=t.0',
      coordinatorName: 'SPE Lead',
      coordinatorContact: 'spe@iitism.ac.in',
      coordinatorEmail: 'spe@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'autoexpo',
      title: 'AutoExpo \'26 — Custom Build & Supercar Showcase',
      category: 'Stage',
      organizerClub: 'Mechismu Automotive',
      venue: 'Main Ground / Parking Arena',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Exhibition of custom fabricated student Formula racecars, electric ATVs, superbikes, modified vehicles, and exotic automotive engineering projects. Open entry for all spectators.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Mechismu AutoExpo Lead',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'angd_game_jam',
      title: 'RRR - A Game Jam (AnGD)',
      category: 'Club',
      organizerClub: 'AnGD (Animation Society)',
      venue: 'Hybrid / NLHC Hall 1',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description: 'RRR — A Game Jam is a 9-day game development challenge where participants turn their ideas into playable games based on a surprise theme using Unity, Unreal, or Godot.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf2g3H4j5K6l7Z8x9C0v1B2n3M4a5S6d7F8g9H0j1K2l3Z4x5/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1fUYT9T9qNVWxPLWHd8co9NVShgXObfpt/view?usp=drivesdk',
      coordinatorName: 'AnGD Team',
      coordinatorContact: 'angd@iitism.ac.in',
      coordinatorEmail: 'angd@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_2_day3',
      title: 'Distinguished Alumni Guest Talk 2',
      category: 'Stage',
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Valedictory keynote address by prominent global IIT (ISM) alumni leaders reflecting on their journey from Dhanbad to leading multinational technology empires.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Guest Relations Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'robo_wars___grand_final',
      title: 'ROBO WARS — THE GRAND FINALE',
      category: 'Flagship',
      organizerClub: 'RoboISM',
      venue: 'RoboWars Armored Arena (SAC Ground)',
      time: '05:00 PM - 06:30 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 1,00,000 Trophy',
      teamSize: 'Finalist Teams',
      description: 'The ultimate clash of titans! The top championship survivor bots battle it out in the sparks-flying Grand Final under stadium lights for the Concetto Centenary RoboWars Trophy.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf0j1K2l3Z4x5C6v7B8n9M0a1S2d3F4g5H6j7K8l9Z0x1C2v3/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'roboism@iitism.ac.in',
      coordinatorEmail: 'roboism@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'star_night_celebrity',
      title: 'CELEBRITY STAR NIGHT (GRAND FINALE)',
      category: 'Stage',
      organizerClub: 'Concetto Organizing Committee',
      venue: 'Main Festival Concert Ground',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'The monumental finale of Concetto\'26! Live in-concert performance by a top Bollywood / Indie headline artist. A colossal sensory experience with 10,000+ attendees, massive stage pyrotechnics, and unforgettable memories. Open entry with fest wristband.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Core Festival Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'prom_night_pre',
      title: 'Prom Night \'26',
      category: 'Stage',
      organizerClub: 'Concetto Social Wing',
      venue: 'SAC Main Floor',
      time: '07:00 PM - 10:00 PM',
      date: 'Oct 7, 2026',
      prizePool: '',
      teamSize: '',
      description: 'The official pre-fest ball and social evening of Concetto\'26. Music, dance, formal red carpet entry, and celebration to kick off the festive spirit.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Social Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'prom_night_pre',
      title: 'Prom Night \'26 — Centenary Kickoff Gala',
      category: 'Pre-Event',
      organizerClub: 'Concetto Core & Cultural Wing',
      venue: 'SAC Amphitheatre & Lawns',
      time: '07:00 PM - 10:30 PM',
      date: 'Oct 6, 2026',
      prizePool: 'Titles & Mementos',
      teamSize: 'Open to All',
      description: 'The signature formal celebration and pre-festival kickoff gala of Concetto\'26 Centenary Edition. Dress in your finest evening wear for an enchanting night of acoustic performances, social networking, student spotlights, and celebrations before competitions begin.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Concetto Core Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '+91 98765 43210',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'kryptos_pre',
      title: 'Kryptos — The National Cryptic Hunt',
      category: 'Pre-Event',
      organizerClub: 'CyberLabs Infosec',
      venue: 'Online (24 Hours)',
      time: '24-Hour Online Hunt',
      date: 'Oct 5-7, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'National online cryptic scavenger hunt. Solve internet puzzles, decode hidden EXIF metadata, audio spectrograms, steganography, and cipher texts across the web to top the national leaderboard.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdSvIrxl8SFP16c3nVU4ZvfCux_QbSUCxSosBAMZMCsHnG_jQ/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1MdZxBX23qUzihYFlPsadoGJfmWvsVacj/edit?usp=drive_link',
      coordinatorName: 'Arav (CyberLabs)',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'movie_night_pre',
      title: 'Open Air Movie Night',
      category: 'Pre-Event',
      organizerClub: 'Concetto Cultural Wing',
      venue: 'Central Ground Amphitheatre',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 7, 2026',
      prizePool: 'Free Entry for All Attendees',
      teamSize: 'Open to All',
      description: 'Under the starlit sky of IIT (ISM) Dhanbad, enjoy an open-air blockbuster movie screening with popcorn, giant projection, and pre-fest community fun.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Cultural Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
  ];

  static final List<CoreTeamMember> team = [
    CoreTeamMember(
      name: 'Prof. Vasanta Govind Kumar Villuri',
      role: 'Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 326 223 5400',
      email: 'vasanta@iitism.ac.in',
      imageUrl: 'assets/about/convener.png',
      year: 'Faculty Convenor',
      quote: 'It gives immense pleasure to welcome you to CONCETTO 2026, the techno-management festival of IIT (ISM) Dhanbad, as we celebrate the institution’s remarkable centenary journey.',
      order: 1,
    ),
    CoreTeamMember(
      name: 'Prof. Niptika Jana',
      role: 'Co-Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 326 223 5401',
      email: 'niptika@iitism.ac.in',
      imageUrl: 'assets/about/co_convener.png',
      year: 'Faculty Co-Convenor',
      quote: 'The future belongs to those who believe in the beauty of their dreams. CONCETTO’26 Centauri Synapse carries forward this century-old spirit.',
      order: 2,
    ),
    CoreTeamMember(
      name: 'Arun Dayal',
      role: '2nd Co-convener',
      vertical: 'Faculty Leadership',
      phone: '+91 95231 25843',
      email: 'arunudai@iitism.ac.in',
      imageUrl: 'assets/about/prof_arun_udai.png',
      year: 'Mechanical Engineering',
      quote:
          'India is now driven by a strong thrust towards startups, indigenous manufacturing, digital public infrastructure, and self-reliance in critical technologies, including medical and defence technologies. This transformation is creating unprecedented opportunities for young innovators to turn ideas into technologies, products, and enterprises that address real-world challenges.\nCONCETTO 2026 provides a platform where curiosity meets technology, creativity meets entrepreneurship, and ideas evolve into meaningful solutions. As IIT (ISM) Dhanbad celebrates a century of excellence, I invite students, researchers, innovators, and industry enthusiasts to use this platform to experiment, collaborate, compete, and create.\nLet us nurture a spirit of innovation that is not limited to solving problems, but aspires to build technologies and enterprises for a self-reliant, technologically empowered India.\n\nWelcome to CONCETTO 2026!\n\n— Arun Dayal\n2nd Co-convener',
      order: 3,
    ),
    CoreTeamMember(
      name: 'Prof. Gopi Krishna Dondapati',
      role: 'Treasurer',
      vertical: 'Faculty Leadership',
      phone: '+91 90003 95922',
      email: 'gopikrishna@iitism.ac.in',
      imageUrl: 'assets/about/prof_gopi_krishna.png',
      year: 'Mining Machinery Engineering',
      quote:
          'It gives me immense pleasure to be a part of Concetto’26 and to contribute towards the successful organization of this celebration of technology, innovation, and creativity. As we commemorate the Centenary Year of IIT (ISM) Dhanbad, this edition holds a special significance as we celebrate a century of excellence, legacy, and learning. As the Treasurer, I believe that responsible financial management, transparency, and accountability are essential for transforming ideas into meaningful experiences. This fest is the result of collective effort, dedication, and teamwork from every individual involved. I sincerely appreciate the commitment of the whole team and look forward to witnessing Concetto’26 become a memorable platform where ideas are shared, talents are showcased, and innovation inspires us all.',
      order: 4,
    ),
    CoreTeamMember(
      name: 'Sourav Dutta',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 87774 59381',
      email: '25dr0207@iitism.ac.in',
      imageUrl: 'assets/about/sourav_dutta.png',
      year: 'Research Scholar',
      quote:
          'It is my immense pleasure to welcome you to Concetto 2026, the annual techno-management fest of IIT (ISM), Dhanbad—where ideas take shape, innovation takes flight, and technology meets purpose. I encourage every participant to explore, experiment, compete, and learn beyond the boundaries of the classroom. May this vibrant convergence inspire curiosity, nurture innovation, and empower young minds to address real-world challenges. Let us celebrate the spirit of discovery and the limitless potential of young minds. Best wishes to all participants and organizers for a remarkable and inspiring Concetto 2026.',
      order: 5,
    ),
    CoreTeamMember(
      name: 'Badal Singh Naik',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 89841 75908',
      email: '25MB0025@iitism.ac.in',
      imageUrl: 'assets/about/badal_singh.png',
      year: 'Management Studies',
      quote:
          'Concetto stands as a vibrant platform where innovation meets imagination and ideas transform into possibilities. My vision has always been to work with dedication, embrace challenges, and strive to deliver the very best. I believe that excellence is not merely a destination, but a continuous journey driven by passion, perseverance, and teamwork. May Concetto continue to inspire young minds, encourage bold thinking, and create an environment where curiosity thrives. I extend my best wishes to the entire team for a successful and enriching edition of Concetto, filled with learning, innovation, and memorable experiences.',
      order: 6,
    ),
    CoreTeamMember(
      name: 'Rahul Kumar',
      role: 'Advisory Committee',
      vertical: 'Student Advisory',
      phone: '+91 82108 80177',
      email: '23dr0121@iitism.ac.in',
      imageUrl: 'assets/about/rahul_kumar.png',
      year: 'Research Scholar',
      quote:
          'It is a privilege to welcome you to Concetto 2026, the premier techno-management festival of IIT (ISM) Dhanbad. As our institute celebrates a monumental century of academic brilliance and innovation, this edition stands as a tribute to our rich legacy and a stepping stone toward a limitless future. A century of excellence has proven that progress belongs to those who dare to rethink the status quo. CONCETTO2026 stands as a testament to our institute’s enduring commitment to scientific brilliance and technical ingenuity. As part of the Advisory Committee, I am honoured to support a festival that turns ambitious concepts into tangible reality. I extend my warmest welcome to all participants. May your time here spark breakthroughs, forge lifelong connections, and inspire you to build a smarter tomorrow.',
      order: 7,
    ),
    CoreTeamMember(
      name: 'Seemala Devi Sri Pranay',
      role: 'Coordinator',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sdsp.jpg',
      year: 'Core Team',
      quote: '',
      order: 8,
    ),
    CoreTeamMember(
      name: 'Adwait Bhor',
      role: 'General Secretary',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sab.jpg',
      year: 'Core Team',
      quote: '',
      order: 9,
    ),
    CoreTeamMember(
      name: 'Jyotiraditya Singh',
      role: 'President, Student\'s Gymkhana',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sjs.jpg',
      year: 'Core Team',
      quote: '',
      order: 10,
    ),
    CoreTeamMember(
      name: 'Mutyala Vinay',
      role: 'Chairperson, Student\'s Gymkhana',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/mutyala_vinay.jpeg',
      year: 'Core Team',
      quote: '',
      order: 11,
    ),
    CoreTeamMember(
      name: 'Parsh J. Chandra',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccparas.jpeg',
      year: 'Core Team',
      quote: '',
      order: 12,
    ),
    CoreTeamMember(
      name: 'Surendra Singh',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccsurendra.jpeg',
      year: 'Core Team',
      quote: '',
      order: 13,
    ),
    CoreTeamMember(
      name: 'Aditya Chauhan',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccaditya.jpeg',
      year: 'Core Team',
      quote: '',
      order: 14,
    ),
    CoreTeamMember(
      name: 'K. Sai Praneeth',
      role: 'Sponsorship Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-ksp.jpg',
      year: 'Core Team',
      quote: '',
      order: 15,
    ),
    CoreTeamMember(
      name: 'Sumit Kumar Bhagat',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-skb.jpg',
      year: 'Core Team',
      quote: '',
      order: 16,
    ),
    CoreTeamMember(
      name: 'Adi Nath Bhawani',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-anb.jpg',
      year: 'Core Team',
      quote: '',
      order: 17,
    ),
    CoreTeamMember(
      name: 'Kushal Kishore',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-kk.jpg',
      year: 'Core Team',
      quote: '',
      order: 18,
    ),
    CoreTeamMember(
      name: 'Manas Gupta',
      role: 'Event Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-mg.jpg',
      year: 'Core Team',
      quote: '',
      order: 19,
    ),
    CoreTeamMember(
      name: 'Gopisetty Harsha Vardhan Naidu',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-gsr.jpg',
      year: 'Core Team',
      quote: '',
      order: 20,
    ),
    CoreTeamMember(
      name: 'Gurtej Singh',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-gt.jpg',
      year: 'Core Team',
      quote: '',
      order: 21,
    ),
    CoreTeamMember(
      name: 'Shreyashkar Singh',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-ss.jpg',
      year: 'Core Team',
      quote: '',
      order: 22,
    ),
    CoreTeamMember(
      name: 'Medithi Sujith',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-sm.jpg',
      year: 'Core Team',
      quote: '',
      order: 23,
    ),
    CoreTeamMember(
      name: 'Manuwada Adithya',
      role: 'Public Relation Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pr.jpeg',
      year: 'Core Team',
      quote: '',
      order: 24,
    ),
    CoreTeamMember(
      name: 'Shivendu Shekhar',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-ss.jpg',
      year: 'Core Team',
      quote: '',
      order: 25,
    ),
    CoreTeamMember(
      name: 'Apoorv Krishna',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-ak.jpg',
      year: 'Core Team',
      quote: '',
      order: 26,
    ),
    CoreTeamMember(
      name: 'Daksh Mor',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-dm.jpg',
      year: 'Core Team',
      quote: '',
      order: 27,
    ),
    CoreTeamMember(
      name: 'Pidathala Tanmayee',
      role: 'Design Team Head',
      vertical: 'Design',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/des-pt.jpg',
      year: 'Core Team',
      quote: '',
      order: 28,
    ),
    CoreTeamMember(
      name: 'Ramala Vivek',
      role: 'Design Team Co-Head',
      vertical: 'Design',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/des-rv.jpg',
      year: 'Core Team',
      quote: '',
      order: 29,
    ),
    CoreTeamMember(
      name: 'Shivam Verma',
      role: 'Operation And Logistics Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-sv.jpg',
      year: 'Core Team',
      quote: '',
      order: 30,
    ),
    CoreTeamMember(
      name: 'Chandragiri Praveen Kumar Reddy',
      role: 'Operation And Logistics Co-Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-cpkr.jpg',
      year: 'Core Team',
      quote: '',
      order: 31,
    ),
    CoreTeamMember(
      name: 'Siddhant Verma',
      role: 'Operation And Logistics Co-Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-sdv.jpg',
      year: 'Core Team',
      quote: '',
      order: 32,
    ),
    CoreTeamMember(
      name: 'Sucheta Ghosal',
      role: 'Web Development Head',
      vertical: 'Development',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/web-sg.jpg',
      year: 'Core Team',
      quote: '',
      order: 33,
    ),
    CoreTeamMember(
      name: 'Ayilamoni Shivani',
      role: 'App Development Head',
      vertical: 'Development',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/app-as.jpg',
      year: 'Core Team',
      quote: '',
      order: 34,
    ),
    CoreTeamMember(
      name: 'Charan Kondapalli',
      role: 'Security Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-ck.jpg',
      year: 'Core Team',
      quote: '',
      order: 35,
    ),
    CoreTeamMember(
      name: 'K Chaitanya',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-kc1.JPG',
      year: 'Core Team',
      quote: '',
      order: 36,
    ),
    CoreTeamMember(
      name: 'Shipal',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-ship.jpg',
      year: 'Core Team',
      quote: '',
      order: 37,
    ),
    CoreTeamMember(
      name: 'Eslavath Sheshank',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-es.jpg',
      year: 'Core Team',
      quote: '',
      order: 38,
    ),
    CoreTeamMember(
      name: 'Rohit Sunkara',
      role: 'Finance Head',
      vertical: 'Finance',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/fin-r.jpg',
      year: 'Core Team',
      quote: '',
      order: 39,
    ),
    CoreTeamMember(
      name: 'Sunka Varun Vashista',
      role: 'Finance Co-Head',
      vertical: 'Finance',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/fin-v.jpg',
      year: 'Core Team',
      quote: '',
      order: 40,
    ),
    CoreTeamMember(
      name: 'Tanishk Kumar Agrawal',
      role: 'Promotion Head',
      vertical: 'Promotion',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/prom-tka.jpg',
      year: 'Core Team',
      quote: '',
      order: 41,
    ),
    CoreTeamMember(
      name: 'Suyash Pandey',
      role: 'Promotion Co-Head',
      vertical: 'Promotion',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/prom-su.jpg',
      year: 'Core Team',
      quote: '',
      order: 42,
    ),
    CoreTeamMember(
      name: 'Keshav Mehnawat',
      role: 'Marketing Head',
      vertical: 'Marketing',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/keshav2.jpeg',
      year: 'Core Team',
      quote: '',
      order: 43,
    ),
    CoreTeamMember(
      name: 'Snehil Kashyap',
      role: 'Marketing Co-Head',
      vertical: 'Marketing',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/mark-sk.jpg',
      year: 'Core Team',
      quote: '',
      order: 44,
    ),
    CoreTeamMember(
      name: 'Mitta Sai Ramana Siddartha',
      role: 'Hospitality Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-sid.jpg',
      year: 'Core Team',
      quote: '',
      order: 45,
    ),
    CoreTeamMember(
      name: 'M Hema Suharshinii',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-hs.jpg',
      year: 'Core Team',
      quote: '',
      order: 46,
    ),
    CoreTeamMember(
      name: 'Keshav Jha',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-kj.jpg',
      year: 'Core Team',
      quote: '',
      order: 47,
    ),
    CoreTeamMember(
      name: 'Nidhi',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-nidhi.jpg',
      year: 'Core Team',
      quote: '',
      order: 48,
    ),
    CoreTeamMember(
      name: 'Sreeja Peesa',
      role: 'Content And Documentation Head',
      vertical: 'Content And Documentation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/cad-sp.jpg',
      year: 'Core Team',
      quote: '',
      order: 49,
    ),
    CoreTeamMember(
      name: 'Rishabh Shukla',
      role: 'Content And Documentation Co-Head',
      vertical: 'Content And Documentation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/cad-rs.jpg',
      year: 'Core Team',
      quote: '',
      order: 50,
    ),
  ];

  static final List<AnnouncementItem> announcements = [
    AnnouncementItem(
      id: 'ann_1',
      title: "Welcome to CONCETTO '26 — Centenary Edition!",
      description:
          "IIT (ISM) Dhanbad proudly presents Concetto'26 with the theme \"Centauri Synapse — Forged Over a Century, Soaring Towards Infinity\". 39 official competitions and ₹ Lakhs in prizes await!",
      timestamp: DateTime(2026, 10, 1, 10, 0),
      tag: 'FEST',
    ),
    AnnouncementItem(
      id: 'ann_2',
      title: 'RoboWars & ChakraVyuh Arena Registrations Live',
      description:
          'Arena battle slots and maze navigation tracks are now open. Register your bots natively or via verified link before deadlines.',
      timestamp: DateTime(2026, 10, 2, 14, 30),
      tag: 'FLAGSHIP',
    ),
    AnnouncementItem(
      id: 'ann_3',
      title: 'Guest Lecture Series — Industry Leaders',
      description:
          'Special sessions with Indrajit Sanyal (Ericsson), Prasath P (HCLTech), and Varun G (Nokia) at Penman Auditorium on September 25, 2026.',
      timestamp: DateTime(2026, 10, 3, 11, 0),
      tag: 'CDC TALKS',
    ),
    AnnouncementItem(
      id: 'ann_4',
      title: 'MasterStack & CaseBlitz',
      description:
          'Overnight hackathon and premier business case study challenge portals are accepting team registrations.',
      timestamp: DateTime(2026, 10, 3, 18, 0),
      tag: 'HACKATHON',
    ),
    AnnouncementItem(
      id: 'ann_5',
      title: 'Fest Dates & Daily Schedule Confirmed',
      description:
          "Concetto'26 runs from October 08 to October 11, 2026 across IIT (ISM) Dhanbad campus. Access the Schedule tab for timeline and venues!",
      timestamp: DateTime(2026, 10, 4, 9, 0),
      tag: 'SCHEDULE',
    ),
  ];
}
