import '../../models/event_item.dart';
import '../../models/core_team_member.dart';
import '../../models/announcement_item.dart';

class MockData {
  static final List<EventItem> events = [
    EventItem(
      id: 'pmx180dc_caseblitz',
      title: 'CaseBlitz \'26',
      category: 'Management',
      tags: ['Management', 'Case Study', 'Business', 'Flagship'],
      organizerClub: 'Product Management × 180DC',
      venue: 'Library 4th floor, 1 NLHC Classroom, GJLT',
      time: '09:00 AM - 04:00 PM (Overnight)',
      date: 'Oct 8, 2026',
      prizePool: '₹ 50,000',
      teamSize: '1 - 4 Members',
      description: 'Official flagship 24-hour business and product case-solving challenge organized by Product Management Club & 180 Degrees Consulting. Teams analyze real-world market disruption problems and deliver strategic pitches to industry judges.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/Caseblitz.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdSvIrxl8SFP16c3nVU4ZvfCux_QbSUCxSosBAMZMCsHnG_jQ/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/16guxLz779Aa_yiCCO6n68UVMimlZmf4U/view?usp=drive_link',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '+91 98765 43210',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'inauguration_ceremony',
      title: 'Grand Inauguration & Fest Overview',
      category: 'Stage',
      tags: ['Stage', 'Flagship', 'Ceremony', 'Inauguration'],
      organizerClub: 'Concetto Advisory & Organizing Committee',
      venue: 'Penman Auditorium',
      time: '05:00 PM - 08:00 PM',
      date: 'Oct 8, 2026',
      prizePool: '',
      teamSize: '',
      description: '''The official grand opening of Concetto'26 Centenary Edition.

INTERNAL TIMELINE:
• 04:00 PM – 05:00 PM: Chief / Guest Arrival
• 05:00 PM – 06:00 PM: INAUGURATION & Lamp Lighting
• 06:00 PM – 07:00 PM: Welcome Address + Director / Chief Guest
• 07:00 PM – 08:00 PM: Concetto Introduction + Fest Overview''',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Concetto Core Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'questree__26',
      title: 'QuesTree ’26',
      category: 'Management',
      tags: ['Management', 'Finance', 'Fintech', 'Analytics'],
      organizerClub: 'Fintech Club',
      venue: 'NLHC Hall 1',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'Finance, analytics, and business acumen quiz hosted by Fintech Club testing economic intuition and data interpretation.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/questree.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScsuG3fa9uePrzfe7hOskmV8nzyF4BE7DalZr3sU1EA_dPUjg/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'fintech@iitism.ac.in',
      coordinatorEmail: 'fintech@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'mathalon',
      title: 'Mathalon',
      category: 'Departmental',
      tags: ['Departmental', 'Mathematics', 'MnC', 'Logic'],
      organizerClub: 'Society of MnC',
      venue: 'NLHC Classrooms',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 2 Members',
      description: 'The competition will cover topics such as basic logic, probability, geometry, number theory, recurrence relations, basic calculus, and other fundamental areas of mathematics, with emphasis on numerical problem-solving rather than lengthy proofs.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSexODKL1fwQDvSY_Ft4Kxa3VJgFL_0FoZ-iAHvz9gIVMFdjfQ/viewform',
      rulebookUrl: 'Mathalon_4.0_Draft.docx',
      coordinatorName: 'MnC Lead',
      coordinatorContact: 'mnc@iitism.ac.in',
      coordinatorEmail: 'mnc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'treasure_hunt_day1',
      title: 'Campus Treasure Hunt Challenge',
      category: 'Fun',
      tags: ['Fun', 'Adventure', 'Campus', 'Mystery'],
      organizerClub: 'Concetto Event Team',
      venue: 'Campus-wide / Student Activity Centre',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 15,000',
      teamSize: '2 - 4 Members',
      description: 'Campus-wide treasure hunt cracking geographical clues, campus trivia, and secret riddles scattered across heritage landmarks of IIT (ISM) Dhanbad.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Event Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'vibehack__26',
      title: 'VibeHack ’26 (DevDash)',
      category: 'Coding',
      tags: ['Coding', 'Web Development', 'Hackathon', 'CyberLabs'],
      organizerClub: 'CyberLabs WebD',
      venue: 'NLHC classrooms',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 40,000',
      teamSize: '1 - 3 Members',
      description: 'DevDash is a beginner-friendly web development hackathon in which teams receive a surprise challenge and rapidly turn it into a creative, functional and presentable website, promoting creativity, teamwork, problem-solving and practical development skills.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/vibehack.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdP94ZSBPRwn5-yYekEj_SXIjY4AzN7PjC2Pbh9FHyaMbTEMg/viewform',
      rulebookUrl: 'DevDash_rulebook.docx',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'game_zone_day1',
      title: 'Game Zone — Team Arena Challenges',
      category: 'Fun',
      tags: ['Fun', 'Gaming', 'Esports', 'Arena'],
      organizerClub: 'Student Activity Centre (SAC)',
      venue: 'SAC Arena & Gaming Lounge',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 15,000',
      teamSize: 'Open to All',
      description: 'Interactive gaming hub with console stations, multiplayer VR battles, mini arcade tournaments, and crowd challenges open all day.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'SAC Team',
      coordinatorContact: 'sac@iitism.ac.in',
      coordinatorEmail: 'sac@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'code_the_cosmos',
      title: 'Code The Cosmos',
      category: 'Coding',
      tags: ['Coding', 'Astronomy', 'Simulation', 'Algorithms'],
      organizerClub: 'ASTC',
      venue: 'Computer Center Lab 1',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'Astrophysical simulation and orbital mechanics programming competition organized by Astronomy & Space Technology Club (ASTC).',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdNc6uuL9p2V6WqHLenLPcHMVxa3d10A-vjy9m3MWql0UqaTw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Hemant',
      coordinatorContact: 'astc@iitism.ac.in',
      coordinatorEmail: 'astc@iitism.ac.in',
      coordinatorPhone: '+91 97721 88990',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'aethera',
      title: 'Aethera',
      category: 'Departmental',
      tags: ['Departmental', 'Sustainability', 'Environment', 'SESE'],
      organizerClub: 'Society of Environmental Science and Engineering (SESE)',
      venue: 'Department of ESE',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 60,000',
      teamSize: '1 - 3 Members',
      description: 'Aethera is a national sustainability case competition by SESE, IIT (ISM) Dhanbad. Teams of up to 3 tackle a live industry sustainability challenge across three rounds: an online screening test, a case deck submission, and The Boardroom, a live online finale where the top 10 teams pitch before an expert panel and face a surprise Curveball round.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/aethera.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf-5tEtvXaG-3uYM7wlIVuzSVSblic6kzvVEYEgskXgy2i2Dg/viewform',
      rulebookUrl: 'https://concetto-ashen.vercel.app/rulebooks/Aethera.pdf',
      coordinatorName: 'SESE Lead',
      coordinatorContact: 'sese@iitism.ac.in',
      coordinatorEmail: 'sese@iitism.ac.in',
      coordinatorPhone: '+91 91234 56789',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'gate_craft',
      title: 'Gate Craft',
      category: 'Electronics',
      tags: ['Electronics', 'Circuits', 'Digital Logic', 'Hardware'],
      organizerClub: 'Electronics & IoT',
      venue: 'NLHC',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'An exciting Minecraft-based technical competition where participants design and build digital logic circuits using Redstone. Participants are challenged to demonstrate logic, creativity, accuracy, and speed within a fixed time.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/gatecraft.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdF5yaVfEX9T-uyzHbxwZYTy5E67mTaWZsqH3ZoXlbPc6cUwA/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/16guxLz779Aa_yiCCO6n68UVMimlZmf4U/view?usp=drive_link',
      coordinatorName: 'Electronics & IoT Lead',
      coordinatorContact: 'electronics_iot@iitism.ac.in',
      coordinatorEmail: 'electronics_iot@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_1_day1',
      title: 'Keynote Guest Talk 1',
      category: 'Stage',
      tags: ['Stage', 'Keynote', 'Guest Talk'],
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Golden Jubilee Lecture Theatre (GJLT)',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Distinguished technical leadership lecture featuring renowned industrialists and engineering visionaries sharing perspectives on cutting-edge deep tech and national progress.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Advisory Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'aeroglide',
      title: 'AeroGlide (Mechismu)',
      category: 'Robotics',
      tags: ['Robotics', 'Aeromodelling', 'UAV', 'Hardware'],
      organizerClub: 'Mechismu',
      venue: 'Lower Grounds / Aeromodelling Arena',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 35,000',
      teamSize: '2 - 5 Members',
      description: 'RC aircraft and UAV design competition. Teams build fixed-wing RC gliders tested on flight duration, payload delivery, aerodynamic efficiency, and spot-landing precision.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/aeroglide.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScsUCGj9GfukLoVypdvMPrvMdRtXaV1EW6sN6KxZXR_1zpqaQ/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'archway_arena__26',
      title: 'Archway Arena ’26',
      category: 'Departmental',
      tags: ['Departmental', 'Civil', 'Structures', 'Engineering'],
      organizerClub: 'Civil Engineering Society',
      venue: 'Civil Department Concourse',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: '2 - 4 Members',
      description: 'Structural truss and arch bridge loading challenge. Teams construct lightweight balsa/popsicle bridge arches tested against dynamic hydraulic point loads until failure.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/archway.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfDRiRUnKTfHYyC6PSyZGzLe1cPkmbrXCO1QvZP0fhXMJ2b1A/viewform',
      rulebookUrl: '',
      coordinatorName: 'Civil Society Lead',
      coordinatorContact: 'civil@iitism.ac.in',
      coordinatorEmail: 'civil@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'forklift__26',
      title: 'ForkLift ’26',
      category: 'Coding',
      tags: ['Coding', 'Blockchain', 'Web3', 'Smart Contracts'],
      organizerClub: 'CyberLabs BlockChain',
      venue: 'Computer Center Lab 3',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 3 Members',
      description: 'Smart contract security, DeFi protocol architecture, and Web3 dApp development hackathon. Teams audit vulnerable Solidity contracts and build decentralized products.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/forklift.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdKkighjJcLM9bNtiTcFv9Iee8Pz9t-j8lM9d9wXV58afTSpw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'quantum_mania',
      title: 'Quantum Mania',
      category: 'Coding',
      tags: ['Coding', 'Quantum Computing', 'Physics', 'Algorithms'],
      organizerClub: 'QARC',
      venue: 'NLHC Classrooms',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 3 Members',
      description: 'Quantum circuit design, teleportation protocol implementation, and quantum algorithm optimization using Qiskit and Pennylane.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd-Q9bPvwxkjvj2VHfUsfMON1xGnmSd0LVGMXfgrJBo5BDZzg/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'qarc@iitism.ac.in',
      coordinatorEmail: 'qarc@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_2_day1',
      title: 'Tech Visionary Guest Talk 2',
      category: 'Stage',
      tags: ['Stage', 'Guest Talk', 'AI'],
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Penman Auditorium',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Inspirational symposium on generative intelligence, autonomous robotics, and emerging computing paradigms shaping the next century.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Advisory Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'logic_odyssey',
      title: 'Logic Odyssey',
      category: 'Coding',
      tags: ['Coding', 'Algorithms', 'Logic', 'Competitive Programming'],
      organizerClub: 'C3',
      venue: 'NLHC (4 halls)',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 25,000',
      teamSize: 'Individual (1 Member)',
      description: 'Logic Odyssey is a ZIO-style, pen-and-paper logic and problem-solving competition featuring 4–6 challenging questions. With 90 minutes to solve, participants will test their logical reasoning, mathematical thinking, analytical ability, and problem-solving skills.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/logicodyssey.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSckWsaTB5QKfhzriT0sWN6a5INiZnVTPsU0bNupnC5upwNP6g/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1WYPSjvhgbtxNUSOyx0kb6k5dx7_jGywL/edit?usp=sharing&ouid=114871654953852545282&rtpof=true&sd=true',
      coordinatorName: 'Vishal',
      coordinatorContact: 'c3@iitism.ac.in',
      coordinatorEmail: 'c3@iitism.ac.in',
      coordinatorPhone: '+91 95234 56789',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'reservoir_making___iadc',
      title: 'Reservoir Making — IADC (Crack the Crude)',
      category: 'Departmental',
      tags: ['Departmental', 'Petroleum', 'Drilling', 'IADC'],
      organizerClub: 'IADC IIT(ISM) Dhanbad SC',
      venue: 'NLHC',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 4 Members',
      description: 'A two-round technical competition designed to test participants’ petroleum engineering knowledge, analytical thinking, and practical skills. The first round features a fast-paced petroleum-themed identification challenge where participants recognize equipment, geological formations, and industry concepts under time pressure. The top-performing teams advance to the second round, where they apply their understanding by designing and constructing a functional reservoir model to demonstrate concepts such as porosity, permeability, fluid migration, and hydrocarbon trapping.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeBTfee9dWp1trn_o-T30CNZ0rEtqt64FjeUD3GfkU0BWrgLg/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1pEjSRus_V5Y90rE7zuBkOs1qcw8Yed2v/view?usp=drivesdk',
      coordinatorName: 'IADC Lead',
      coordinatorContact: 'iadc@iitism.ac.in',
      coordinatorEmail: 'iadc@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'comedy_night_live',
      title: 'CELEBRITY COMEDY NIGHT',
      category: 'Stage',
      tags: ['Stage', 'Pronite', 'Comedy', 'Entertainment'],
      organizerClub: 'Concetto Cultural Wing',
      venue: 'Penman Auditorium',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 9, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Star stand-up comedy performance bringing India\'s top standup comedian live on stage for an evening of side-splitting laughter and satire. Entry begins at 7:00 PM.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Cultural Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'tinas__26',
      title: 'TiNAS ’26',
      category: 'Coding',
      tags: ['Coding', 'Cybersecurity', 'CTF', 'Infosec', 'Flagship'],
      organizerClub: 'CyberLabs Infosec',
      venue: 'Computer Center Lab 2',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 45,000',
      teamSize: '1 - 3 Members',
      description: 'Flagship 24-hour jeopardy and attack-defense Capture The Flag tournament covering binary exploitation, reverse engineering, web security, cryptography, and forensics.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/tinas.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSez_u7IF7h3p0F0Y4fWAKCqy5pjlo9jFpl9p80J9XfLlh7HbQ/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'sparkathon',
      title: 'Sparkathon 2.0',
      category: 'Departmental',
      tags: ['Departmental', 'Electronics', 'Hardware', 'IoT', 'Flagship'],
      organizerClub: 'Society of Electronics Engineers ',
      venue: 'NLHC',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 50,000',
      teamSize: '2 - 4 Members',
      description: 'Sparkathon is an innovation-oriented technical event that encourages participants to develop creative and practical solutions to real-world engineering problems. Participants will be required to analyze the given problem statement, formulate an innovative approach, and present their proposed solution to a panel.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/sparkathon.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeBwamRY0l9qYbZauwxnG6Ir0L8JIesSPLYwnhkuhom5zpUEA/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1XGoeOKbqw8zve-K4h1saq9LQ91wJuWGb/view?usp=drivesdk',
      coordinatorName: 'SEE Lead',
      coordinatorContact: 'see@iitism.ac.in',
      coordinatorEmail: 'see@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'minute_to_win_it',
      title: 'Minute to Win It — Fast Reflex Games',
      category: 'Fun',
      tags: ['Fun', 'Games', 'Reflex', 'Informal'],
      organizerClub: 'Concetto Fun Team',
      venue: 'SAC Lawn Canopy',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 10, 2026',
      prizePool: 'Exciting Hampers & Swag',
      teamSize: 'Solo / Duo',
      description: 'Fast-paced 60-second table challenges, balance games, card towers, and reflex competitions with instant prizes.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Fun Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'escape_room',
      title: 'Escape Room',
      category: 'Departmental',
      tags: ['Departmental', 'Mathematics', 'Puzzles', 'Fun'],
      organizerClub: 'Maths Club',
      venue: 'NLHC Classrooms',
      time: '10:00 AM - 11:00 AM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 20,000',
      teamSize: '2 - 4 Members',
      description: 'Immersive logic and puzzle escape game where teams decode lock codes, discover hidden cryptographic keys, and break out within 45 minutes.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSccueiwWC2vu7bAu5mG6nz1qKqTmQuGd20jJpDof9jeIQp8CA/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'mathsclub@iitism.ac.in',
      coordinatorEmail: 'mathsclub@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'edge_ai_challenge',
      title: 'Edge AI Challenge',
      category: 'Electronics',
      tags: ['Electronics', 'Embedded', 'IoT', 'Hardware'],
      organizerClub: 'Electronics & IoT',
      venue: 'NLHC',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 3 Members',
      description: 'A team-based technical competition where participants develop, optimize, and deploy a lightweight AI model on resource-constrained embedded hardware. Teams are judged on accuracy, speed, resource efficiency, and successful edge deployment.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/edgeai.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdgmnRAb94DDD-h7D3V6ijVmyUYyd6LeVDdIxv2dsH3p97YNQ/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1NM1K04y-SFi-x8o9y7VprX2pcn0oeWBO/view?usp=sharing',
      coordinatorName: 'Electronics & IoT Lead',
      coordinatorContact: 'electronics_iot@iitism.ac.in',
      coordinatorEmail: 'electronics_iot@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'mlmte_quiz_club_quiz',
      title: 'MLMTE Quiz Club Quiz',
      category: 'Departmental',
      tags: ['Departmental', 'Mining', 'Quiz', 'Core'],
      organizerClub: 'Quiz Club',
      venue: 'Mining Department Lecture Hall',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '2 Members',
      description: 'National technical quiz on mining machinery, mineral exploration, metallurgy, sustainable mineral extraction, and geological engineering.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdL84QU92qx3bv6GSLQe3-O93Avqj3pkNqQCbWo7sK_5SxOHg/viewform',
      rulebookUrl: '',
      coordinatorName: 'Hemant',
      coordinatorContact: 'quizclub@iitism.ac.in',
      coordinatorEmail: 'quizclub@iitism.ac.in',
      coordinatorPhone: '+91 97721 88990',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'hands_on_workshop_day2',
      title: 'Hands-on Tech Workshop',
      category: 'Coding',
      tags: ['Coding', 'Workshop', 'AI', 'Hands-on'],
      organizerClub: 'Technical Council',
      venue: 'NLHC Hall 3',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 10, 2026',
      prizePool: 'Certificates of Merit',
      teamSize: 'Open Registration',
      description: 'Industry-led practical developer masterclass focused on deploying production LLMs, fine-tuning lightweight models, and low-latency inference on GPUs.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Workshop Cell',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'angd_3d_animation',
      title: 'AnGD 3D Animation',
      category: 'Design',
      tags: ['Design', '3D', 'Animation', 'Creative', 'CGI'],
      organizerClub: 'AnGd',
      venue: 'Online',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 3 Members',
      description: 'Then. Now. Next. is a 15-day 3D animation competition where participants bring their creativity to life through 3D modelling, animation, and visual storytelling based on a given theme. Showcase your technical and artistic skills and create something truly engaging for Concetto’26.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeqHA0yttderk7EIO-NjMEsXkRhrIkzIsTGVxtSw3-v_e0llQ/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1fEXGOvFQEKAH0X7etImMUJirPPyiQFnM/view?usp=drivesdk',
      coordinatorName: 'Hemant',
      coordinatorContact: 'angd@iitism.ac.in',
      coordinatorEmail: 'angd@iitism.ac.in',
      coordinatorPhone: '+91 97721 88990',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_1_day2',
      title: 'Industry Leader Guest Talk 1',
      category: 'Stage',
      tags: ['Stage', 'Guest Talk', 'Leadership'],
      organizerClub: 'Concetto Advisory Committee',
      venue: 'GJLT',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Fireside conversation with global technology founders on scaling hardware startups, semiconductor manufacturing in India, and venture funding.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Advisory Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'chakravyuh',
      title: 'ChakraVyuh',
      category: 'Robotics',
      tags: ['Robotics', 'RoboISM', 'Autonomous', 'Maze', 'Flagship'],
      organizerClub: 'RoboISM',
      venue: 'SAC Basketball Arena',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 40,000',
      teamSize: '2 - 4 Members',
      description: 'Autonomous line-maze solving robot competition. Bots navigate multi-branched dynamic tracks with loops, line discontinuities, and obstacle avoidance.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/chakravyuh.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfTL9X7sPZNZAnW1BcERs9v72jQXvlr99s4l89U4I8PGdyn0g/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'roboism@iitism.ac.in',
      coordinatorEmail: 'roboism@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'alchemist',
      title: 'ALCHEMIST',
      category: 'Departmental',
      tags: ['Departmental', 'Chemical', 'Process Engineering', 'ChES'],
      organizerClub: 'Chemical Engineering Society',
      venue: 'Chemical Engineering Labs',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '2 - 3 Members',
      description: 'Chemical process optimization and reaction kinetics design sprint. Teams design an efficient separation column and simulate real refinery plant economics.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeGumZlCZfIZok0Mxd9sc_15VpehTrime3uczr2gLQpUKJP_g/viewform',
      rulebookUrl: '',
      coordinatorName: 'ChES Lead',
      coordinatorContact: 'ches@iitism.ac.in',
      coordinatorEmail: 'ches@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'stunt_show_mechismu',
      title: 'MECHISMU EXTREME BIKE STUNT SHOW',
      category: 'Stage',
      tags: ['Stage', 'Stunts', 'Extreme', 'Automotive'],
      organizerClub: 'Mechismu',
      venue: 'Main Centenary Ground',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'High-octane motorcycle acrobatic stunt show featuring professional riders executing burnouts, high-speed drifts, and wheelies on a custom stadium course.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'convcup__26',
      title: 'ConvCup ’26',
      category: 'Coding',
      tags: ['Coding', 'Machine Learning', 'AI', 'Data Science'],
      organizerClub: 'CyberLabs ML',
      venue: 'Computer Center Lab 1',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 40,000',
      teamSize: '1 - 3 Members',
      description: 'Machine learning Kaggle-style hackathon. Build predictive deep learning models for high-dimensional tabular, audio, or image classification datasets.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/convcup.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSczTGuyBed05pCtxNKc_fovb4Gv2l5QwGw03Aw5drHhwi6gUw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'autonav',
      title: 'AutoNav',
      category: 'Robotics',
      tags: ['Robotics', 'Autonomous', 'Computer Vision', 'RC'],
      organizerClub: 'Mechismu',
      venue: 'SAC Lawn Arena',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 35,000',
      teamSize: '2 - 4 Members',
      description: 'Autonomous vehicle and RC robotics competition featuring computer vision lane tracking, ultrasonic obstacle avoidance, and dynamic speed profiling.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/autonav.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdnrR_Y-UnVpABHiIeJhWOZMN0eRJNjB5XVfCWb-C8NJwBmLg/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_2_day2',
      title: 'Innovation Keynote Guest Talk 2',
      category: 'Stage',
      tags: ['Stage', 'Guest Talk', 'Innovation'],
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Penman Auditorium',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Keynote on Quantum Advantage, Artificial General Intelligence, and the role of engineering students in transforming Indian deep tech on the global stage.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Advisory Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'q_blueprint',
      title: 'Q-Blueprint',
      category: 'Coding',
      tags: ['Coding', 'Quantum', 'Algorithms', 'Qiskit'],
      organizerClub: 'QARC',
      venue: 'NLHC Classrooms',
      time: '05:00 PM - 06:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 25,000',
      teamSize: '1 - 2 Members',
      description: 'Quantum circuit optimization sprint. Create pulse-level schedules, implement error mitigation techniques, and benchmark quantum fidelity.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSfxXvIIU3nt3Oph0QYUTYQNwrDCByfp_cvG3naYQWtJ3NgBHQ/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'qarc@iitism.ac.in',
      coordinatorEmail: 'qarc@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'equity_auction',
      title: 'Equity Auction',
      category: 'Management',
      tags: ['Management', 'Finance', 'Stocks', 'Auction'],
      organizerClub: 'Fintech',
      venue: 'Online',
      time: '06:00 PM - 07:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'Equity Auction is a high-stakes finance-simulation event where teams of 1-4 members take on the role of investors. Participants must navigate market uncertainty, execute strategic negotiations, and react dynamically to sudden market shocks.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/equityauction.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSe0AuJyah_VonZsZfXG05nHb-lhRYBxA2LGtOb1OZsc8tjAzw/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1REV4cZH4sWdGNWNmw9l6uzvRLYAyS_qIIhY3595iLNE/edit?usp=sharing',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'fintech@iitism.ac.in',
      coordinatorEmail: 'fintech@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'dj_night_party',
      title: 'MEGA EDM & DJ NIGHT',
      category: 'Stage',
      tags: ['Stage', 'Pronite', 'EDM', 'Music'],
      organizerClub: 'Concetto Cultural Wing',
      venue: 'Main Centenary Ground',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 10, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Centenary EDM celebration featuring top national electronic music artists, pyrotechnic displays, laser show, and massive open dance floors. Gathering starts at 7:00 PM.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Cultural Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'pixel_perfect__26',
      title: 'Pixel Perfect ’26',
      category: 'Design',
      tags: ['Design', 'UI/UX', 'Figma', 'Prototyping', 'Product Design'],
      organizerClub: 'CyberLabs UI/UX',
      venue: 'NLHC Lab 4',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 2 Members',
      description: 'Product redesign and design-system hackathon. Teams solve complex UX friction points and build high-fidelity interactive Figma prototypes judged on design thinking.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/pixelperfect.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSf0r-Of_qJipnNzxYWq50Qu_fSUM4Q918Sxt4m3QBlSZlKVSQ/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'seek_the_civil_geek__26',
      title: 'Seek the Civil Geek ’26',
      category: 'Departmental',
      tags: ['Departmental', 'Civil', 'Structures', 'Quiz'],
      organizerClub: 'Civil Engineering Society',
      venue: 'Civil Department Seminar Hall',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '2 Members',
      description: 'National civil engineering and structural aptitude quiz covering geotechnical mechanics, concrete technology, transportation systems, and surveying.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSezqSyxY_VpUGS_mbQKuLQQ9mQhK3iVJXetde4oXxGluHo2fw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Civil Society Lead',
      coordinatorContact: 'civil@iitism.ac.in',
      coordinatorEmail: 'civil@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'fun_games_arena',
      title: 'Fun Games Arena & Interactive Booths',
      category: 'Fun',
      tags: ['Fun', 'Carnival', 'Interactive', 'Games'],
      organizerClub: 'Concetto Fun Team',
      venue: 'SAC Lawn & Food Street',
      time: '09:00 AM - 10:00 AM',
      date: 'Oct 11, 2026',
      prizePool: 'Prizes & Goodies',
      teamSize: 'Open Entry',
      description: 'All-day festival carnival featuring outdoor obstacle runs, giant board games, laser tag arenas, and photo booths across the festival concourse.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Fun Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'robowars',
      title: 'ROBO WARS — Combat Robotics Championship',
      category: 'Robotics',
      tags: ['Robotics', 'RoboISM', 'Combat', 'Arena', 'Flagship'],
      organizerClub: 'RoboISM',
      venue: 'RoboWars Armored Arena (SAC Ground)',
      time: '10:00 AM - 06:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 1,00,000 Trophy',
      teamSize: '2 - 6 Members',
      description: 'The undisputed colosseum of Concetto! Heavyweight custom combat robots clash in a reinforced polycarbonate cage until destruction or knockout.\n\nINTERNAL TIMELINE:\n• 10:00 AM – 12:00 PM: RoboWars — Main Rounds\n• 05:00 PM – 06:00 PM: ROBO WARS — GRAND FINAL under stadium spotlights!',
      posterUrl: 'https://concetto-ashen.vercel.app/events/robowars.webp',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSecHwG-hds8YQwvYlRvQ9EQfxBxZnNhtHOb8Ia4WEazvAqMyw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'roboism@iitism.ac.in',
      coordinatorEmail: 'roboism@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'emerging_tech_workshop_day3',
      title: 'Next-Gen AI & Robotics Workshop',
      category: 'Robotics',
      tags: ['Robotics', 'AI', 'Workshop', 'Hardware'],
      organizerClub: 'Technical Council',
      venue: 'NLHC Hall 2',
      time: '10:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: 'Participation Credentials',
      teamSize: 'Open Registration',
      description: 'Expert-led intensive workshop on ROS2 (Robot Operating System), SLAM algorithms, and sensor fusion for autonomous mobile robots.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Workshop Cell',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'sbt_quiz',
      title: 'SBT Quiz',
      category: 'Departmental',
      tags: ['Departmental', 'Biotechnology', 'Quiz'],
      organizerClub: 'Quiz Club',
      venue: 'Bio-Engineering Seminar Room',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 20,000',
      teamSize: '1 - 2 Members',
      description: 'National biotechnology and life sciences quiz covering synthetic biology, genetic engineering, bioinformatics, and biomedical device innovations.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScV31qs0QIyILLQL1AU_hwJeusJGzAxTqrRsHBdllDD67URHw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Hemant',
      coordinatorContact: 'quizclub@iitism.ac.in',
      coordinatorEmail: 'quizclub@iitism.ac.in',
      coordinatorPhone: '+91 97721 88990',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'fault_hunt',
      title: 'Fault Hunt',
      category: 'Departmental',
      tags: ['Departmental', 'Electronics', 'Circuits', 'PCB', 'Hardware', 'Debugging'],
      organizerClub: 'Society of Electronics Engineers ',
      venue: 'NLHC',
      time: '11:00 AM - 12:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 25,000',
      teamSize: '2 - 4 Members',
      description: 'Fault Hunt is a circuit-analysis and troubleshooting-based technical event designed to test participants\' understanding of electronic circuits, simulation, debugging, and analytical reasoning. The event will challenge participants to identify faults in circuits and justify their findings through systematic analysis.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/faulthunt.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeiwkbItv5Nq71q8_zA8TBgJXyhlAip2wzGLRr8OTEnxPQKlQ/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1erw12jQTDZzvAPLUY6Y8e1QDNbaQHnqh/view?usp=drivesdk',
      coordinatorName: 'SEE Lead',
      coordinatorContact: 'see@iitism.ac.in',
      coordinatorEmail: 'see@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'appsurd__26',
      title: 'AppSurD ’26',
      category: 'Coding',
      tags: ['Coding', 'Mobile', 'App Development', 'Flutter'],
      organizerClub: 'CyberLabs AppD',
      venue: 'Computer Center Lab 2',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '1 - 4 Members',
      description: 'Mobile application development hackathon in Flutter, Android, or React Native building innovative offline-first mobile apps for real problems.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/appsurd.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdwWOSJ5E48lebqLnmXchqEbqC_C1DFSGfC6DJHLatm29C8ng/viewform',
      rulebookUrl: '',
      coordinatorName: 'Arav',
      coordinatorContact: 'cyberlabs@iitism.ac.in',
      coordinatorEmail: 'cyberlabs@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_1_day3',
      title: 'Futurist Keynote Guest Talk 1',
      category: 'Stage',
      tags: ['Stage', 'Guest Talk', 'Futurism'],
      organizerClub: 'Concetto Advisory Committee',
      venue: 'GJLT',
      time: '12:00 PM - 01:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Distinguished lecture on clean energy transition, sustainable mining practices, and geopolitical space exploration in the 21st century.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Advisory Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'code_wars',
      title: 'Code Wars',
      category: 'Coding',
      tags: ['Coding', 'Competitive Programming', 'Algorithms', '1v1', 'Flagship'],
      organizerClub: 'C3',
      venue: 'NLHC Lab/ library 4th floor',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 35,000',
      teamSize: 'Team of 3',
      description: 'Code Wars is an ICPC-style competitive programming team contest where teams of exactly 3 participants solve algorithmic problems within 2.5–3 hours. The contest tests problem-solving, coding skills, algorithmic thinking, and teamwork.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/codewars.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLScyVg0RlpWugmEcvoXBjv_IioXpNF52GHYktbs1_uzpGFKDOA/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1MdZxBX23qUzihYFlPsadoGJfmWvsVacj/edit?usp=drive_link&ouid=114871654953852545282&rtpof=true&sd=true',
      coordinatorName: 'Vishal',
      coordinatorContact: 'c3@iitism.ac.in',
      coordinatorEmail: 'c3@iitism.ac.in',
      coordinatorPhone: '+91 95234 56789',
      isFlagship: true,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'spe_event',
      title: 'SPE Event (Stand Tall - Jack Up Challenge)',
      category: 'Departmental',
      tags: ['Departmental', 'Petroleum', 'Offshore', 'SPE'],
      organizerClub: 'SPE IIT(ISM) Dhanbad',
      venue: 'Petroleum Department',
      time: '02:00 PM - 03:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 30,000',
      teamSize: '2 - 4 Members',
      description: 'Offshore rig design and structural integrity challenge testing stability, ocean current resistance, and drilling capability in offshore basins.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc9GdmE6XUHWjHZU2Ais_diInsy60TK7825chyPxQ4x0fZ2gA/viewform',
      rulebookUrl: 'https://docs.google.com/document/d/1JwM-sddXjfyiTjDHzsaxUMILP-PF7oaTVOOZlWS3Iv0/edit?hl=en&tab=t.0',
      coordinatorName: 'SPE Lead',
      coordinatorContact: 'spe@iitism.ac.in',
      coordinatorEmail: 'spe@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'autoexpo',
      title: 'AutoExpo',
      category: 'Stage',
      tags: ['Stage', 'Automotive', 'Exhibition', 'Supercars'],
      organizerClub: 'Mechismu',
      venue: 'Main Centenary Ground',
      time: '03:00 PM - 04:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Exhibition of custom fabricated student Formula racecars, electric ATVs, superbikes, modified vehicles, and exotic automotive engineering projects. Open entry for all spectators.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSctS1LsOcJ1hKPcWviCkS8n0stpTfjkZtSyFjfHnuHk1T7Kyw/viewform',
      rulebookUrl: '',
      coordinatorName: 'Utkarsh',
      coordinatorContact: 'mechismu@iitism.ac.in',
      coordinatorEmail: 'mechismu@iitism.ac.in',
      coordinatorPhone: '+91 94140 12345',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'angd_game_jam',
      title: 'AnGD Game Jam (RRR-A Game Jam)',
      category: 'Design',
      tags: ['Design', 'Game Development', 'Creative', 'AnGD'],
      organizerClub: 'AnGd',
      venue: 'Hybrid (NLHC 1 ROOM)',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '₹ 35,000',
      teamSize: '1 - 4 Members',
      description: 'RRR – A Game Jam is a 9-day game development challenge where participants turn their ideas into playable games based on a surprise theme. Teams can use any game engine, experiment with gameplay and creativity, and present their final creation at Concetto’26.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd6-dGfbYM_G4Ma9yFeEOkp0MGd7uEPJhQua-sB1xScTGpIRg/viewform',
      rulebookUrl: 'https://drive.google.com/file/d/1fUYT9T9qNVWxPLWHd8co9NVShgXObfpt/view?usp=drivesdk',
      coordinatorName: 'Hemant',
      coordinatorContact: 'angd@iitism.ac.in',
      coordinatorEmail: 'angd@iitism.ac.in',
      coordinatorPhone: '+91 97721 88990',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'guest_talk_2_day3',
      title: 'Distinguished Alumni Guest Talk 2',
      category: 'Stage',
      tags: ['Stage', 'Guest Talk', 'Alumni'],
      organizerClub: 'Concetto Advisory Committee',
      venue: 'Penman Auditorium',
      time: '04:00 PM - 05:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: 'Valedictory keynote address by prominent global IIT (ISM) alumni leaders reflecting on their journey from Dhanbad to leading multinational technology empires.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Advisory Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'star_night_celebrity',
      title: 'CELEBRITY STAR NIGHT (GRAND FINALE)',
      category: 'Stage',
      tags: ['Stage', 'Pronite', 'Concert', 'Celebrity', 'Flagship'],
      organizerClub: 'Concetto Organizing Committee',
      venue: 'Main Festival Concert Ground',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 11, 2026',
      prizePool: '',
      teamSize: '',
      description: '''The monumental finale of Concetto'26! Live in-concert performance by a top Bollywood / Indie headline artist. A colossal sensory experience with 10,000+ attendees, massive stage pyrotechnics, and unforgettable memories. Open entry with fest wristband.

INTERNAL TIMELINE:
• 06:30 PM – 07:30 PM: Star Night Preparation & Sound Check
• 07:30 PM – 08:00 PM: Star Night Gates Open & Entry
• 08:00 PM – 11:00 PM: STAR NIGHT LIVE IN-CONCERT''',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Core Festival Committee',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: true,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'prom_night_pre',
      title: 'Prom Night \'26 — Centenary Kickoff Gala',
      category: 'Pre-Event',
      tags: ['Pre-Events', 'Gala', 'Social', 'Cultural'],
      organizerClub: 'Concetto Core & Cultural Wing',
      venue: 'SAC Amphitheatre & Lawns',
      time: '07:00 PM - 10:30 PM',
      date: 'Oct 6, 2026',
      prizePool: 'Titles & Mementos',
      teamSize: 'Open to All',
      description: 'The signature formal celebration and pre-festival kickoff gala of Concetto\'26 Centenary Edition. Dress in your finest evening wear for an enchanting night of acoustic performances, social networking, student spotlights, and celebrations before competitions begin.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Concetto Core Team',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
    EventItem(
      id: 'kryptoes_pre',
      title: 'Kryptoes \'26 — Solo Dance Showdown',
      category: 'Pre-Event',
      tags: ['Pre-Events', 'Dance', 'Stage', 'Cultural', 'LITM', 'Solo Dance'],
      organizerClub: 'LITM (Legends In The Making)',
      venue: 'Penman Auditorium Stage',
      time: '06:00 PM - 09:30 PM',
      date: 'Oct 6, 2026',
      prizePool: '₹ 20,000',
      teamSize: 'Solo (1 Performer)',
      description: 'The premier solo dance face-off at IIT (ISM) Dhanbad organized by LITM (Legends In The Making). Freshers and campus dancers clash on stage across Hip Hop, Freestyle, Popping, Waacking, and Contemporary styles to crown the ultimate dance champion of Concetto!',
      posterUrl: 'assets/about/glimpse2.png',
      registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdSvIrxl8SFP16c3nVU4ZvfCux_QbSUCxSosBAMZMCsHnG_jQ/viewform',
      rulebookUrl: '',
      coordinatorName: 'LITM Lead',
      coordinatorContact: 'litm@iitism.ac.in',
      coordinatorEmail: 'litm@iitism.ac.in',
      coordinatorPhone: '+91 83412 60805',
      isFlagship: false,
      isWatchableOnly: false,
    ),
    EventItem(
      id: 'movie_night_pre',
      title: 'Open Air Movie Night',
      category: 'Pre-Event',
      tags: ['Pre-Events', 'Cinema', 'Fun', 'Screening'],
      organizerClub: 'Concetto Cultural Wing',
      venue: 'Central Ground Amphitheatre',
      time: '08:00 PM - 11:00 PM',
      date: 'Oct 7, 2026',
      prizePool: 'Free Entry for All Attendees',
      teamSize: 'Open to All',
      description: 'Under the starlit sky of IIT (ISM) Dhanbad, enjoy an open-air blockbuster movie screening with popcorn, giant projection, and pre-fest community fun.',
      posterUrl: 'https://concetto-ashen.vercel.app/events/general.png',
      registrationUrl: '',
      rulebookUrl: '',
      coordinatorName: 'Cultural Wing',
      coordinatorContact: 'concetto@iitism.ac.in',
      coordinatorEmail: 'concetto@iitism.ac.in',
      coordinatorPhone: '',
      isFlagship: false,
      isWatchableOnly: true,
    ),
  ];

  static final List<CoreTeamMember> team = [
    CoreTeamMember(
      name: 'Prof. Vasanta Govind Kumar Villuri',
      role: 'Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 326 223 5400',
      email: 'vasanta@iitism.ac.in',
      imageUrl: 'assets/about/convener.png',
      year: 'Faculty Convenor',
      quote: 'It gives immense pleasure to welcome you to CONCETTO 2026, the techno-management festival of IIT (ISM) Dhanbad, as we celebrate the institution’s remarkable centenary journey.',
      order: 1,
    ),
    CoreTeamMember(
      name: 'Prof. Niptika Jana',
      role: 'Co-Convenor',
      vertical: 'Faculty Leadership',
      phone: '+91 326 223 5401',
      email: 'niptika@iitism.ac.in',
      imageUrl: 'assets/about/co_convener.png',
      year: 'Faculty Co-Convenor',
      quote: 'The future belongs to those who believe in the beauty of their dreams. CONCETTO’26 Centauri Synapse carries forward this century-old spirit.',
      order: 2,
    ),
    CoreTeamMember(
      name: 'Arun Dayal',
      role: '2nd Co-convener',
      vertical: 'Faculty Leadership',
      phone: '+91 95231 25843',
      email: 'arunudai@iitism.ac.in',
      imageUrl: 'assets/about/prof_arun_udai.png',
      year: 'Mechanical Engineering',
      quote:
          'India is now driven by a strong thrust towards startups, indigenous manufacturing, digital public infrastructure, and self-reliance in critical technologies, including medical and defence technologies. This transformation is creating unprecedented opportunities for young innovators to turn ideas into technologies, products, and enterprises that address real-world challenges.\nCONCETTO 2026 provides a platform where curiosity meets technology, creativity meets entrepreneurship, and ideas evolve into meaningful solutions. As IIT (ISM) Dhanbad celebrates a century of excellence, I invite students, researchers, innovators, and industry enthusiasts to use this platform to experiment, collaborate, compete, and create.\nLet us nurture a spirit of innovation that is not limited to solving problems, but aspires to build technologies and enterprises for a self-reliant, technologically empowered India.\n\nWelcome to CONCETTO 2026!',
      order: 3,
    ),
    CoreTeamMember(
      name: 'Prof. Gopi Krishna Dondapati',
      role: 'Treasurer',
      vertical: 'Faculty Leadership',
      phone: '+91 90003 95922',
      email: 'gopikrishna@iitism.ac.in',
      imageUrl: 'assets/about/prof_gopi_krishna.png',
      year: 'Mining Machinery Engineering',
      quote:
          'It gives me immense pleasure to be a part of Concetto’26 and to contribute towards the successful organization of this celebration of technology, innovation, and creativity. As we commemorate the Centenary Year of IIT (ISM) Dhanbad, this edition holds a special significance as we celebrate a century of excellence, legacy, and learning. As the Treasurer, I believe that responsible financial management, transparency, and accountability are essential for transforming ideas into meaningful experiences. This fest is the result of collective effort, dedication, and teamwork from every individual involved. I sincerely appreciate the commitment of the whole team and look forward to witnessing Concetto’26 become a memorable platform where ideas are shared, talents are showcased, and innovation inspires us all.',
      order: 4,
    ),
    CoreTeamMember(
      name: 'Sourav Dutta',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 87774 59381',
      email: '25dr0207@iitism.ac.in',
      imageUrl: 'assets/about/sourav_dutta.png',
      year: 'Research Scholar',
      quote:
          'It is my immense pleasure to welcome you to Concetto 2026, the annual techno-management fest of IIT (ISM), Dhanbad—where ideas take shape, innovation takes flight, and technology meets purpose. I encourage every participant to explore, experiment, compete, and learn beyond the boundaries of the classroom. May this vibrant convergence inspire curiosity, nurture innovation, and empower young minds to address real-world challenges. Let us celebrate the spirit of discovery and the limitless potential of young minds. Best wishes to all participants and organizers for a remarkable and inspiring Concetto 2026.',
      order: 5,
    ),
    CoreTeamMember(
      name: 'Badal Singh Naik',
      role: 'Student Advisor',
      vertical: 'Student Advisory',
      phone: '+91 89841 75908',
      email: '25MB0025@iitism.ac.in',
      imageUrl: 'assets/about/badal_singh.png',
      year: 'Management Studies',
      quote:
          'Concetto stands as a vibrant platform where innovation meets imagination and ideas transform into possibilities. My vision has always been to work with dedication, embrace challenges, and strive to deliver the very best. I believe that excellence is not merely a destination, but a continuous journey driven by passion, perseverance, and teamwork. May Concetto continue to inspire young minds, encourage bold thinking, and create an environment where curiosity thrives. I extend my best wishes to the entire team for a successful and enriching edition of Concetto, filled with learning, innovation, and memorable experiences.',
      order: 6,
    ),
    CoreTeamMember(
      name: 'Rahul Kumar',
      role: 'Advisory Committee',
      vertical: 'Student Advisory',
      phone: '+91 82108 80177',
      email: '23dr0121@iitism.ac.in',
      imageUrl: 'assets/about/rahul_kumar.png',
      year: 'Research Scholar',
      quote:
          'It is a privilege to welcome you to Concetto 2026, the premier techno-management festival of IIT (ISM) Dhanbad. As our institute celebrates a monumental century of academic brilliance and innovation, this edition stands as a tribute to our rich legacy and a stepping stone toward a limitless future. A century of excellence has proven that progress belongs to those who dare to rethink the status quo. CONCETTO2026 stands as a testament to our institute’s enduring commitment to scientific brilliance and technical ingenuity. As part of the Advisory Committee, I am honoured to support a festival that turns ambitious concepts into tangible reality. I extend my warmest welcome to all participants. May your time here spark breakthroughs, forge lifelong connections, and inspire you to build a smarter tomorrow.',
      order: 7,
    ),
    CoreTeamMember(
      name: 'Seemala Devi Sri Pranay',
      role: 'Coordinator',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sdsp.jpg',
      year: 'Core Team',
      quote: '',
      order: 8,
    ),
    CoreTeamMember(
      name: 'Adwait Bhor',
      role: 'General Secretary',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sab.jpg',
      year: 'Core Team',
      quote: '',
      order: 9,
    ),
    CoreTeamMember(
      name: 'Jyotiraditya Singh',
      role: 'President, Student\'s Gymkhana',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sjs.jpg',
      year: 'Core Team',
      quote: '',
      order: 10,
    ),
    CoreTeamMember(
      name: 'Mutyala Vinay',
      role: 'Chairperson, Student\'s Gymkhana',
      vertical: 'Secretariat',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/mutyala_vinay.jpeg',
      year: 'Core Team',
      quote: '',
      order: 11,
    ),
    CoreTeamMember(
      name: 'Parsh J. Chandra',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccparas.jpeg',
      year: 'Core Team',
      quote: '',
      order: 12,
    ),
    CoreTeamMember(
      name: 'Surendra Singh',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccsurendra.jpeg',
      year: 'Core Team',
      quote: '',
      order: 13,
    ),
    CoreTeamMember(
      name: 'Aditya Chauhan',
      role: 'Co-coordinator',
      vertical: 'Co-Coordinators',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/ccaditya.jpeg',
      year: 'Core Team',
      quote: '',
      order: 14,
    ),
    CoreTeamMember(
      name: 'K. Sai Praneeth',
      role: 'Sponsorship Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-ksp.jpg',
      year: 'Core Team',
      quote: '',
      order: 15,
    ),
    CoreTeamMember(
      name: 'Sumit Kumar Bhagat',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-skb.jpg',
      year: 'Core Team',
      quote: '',
      order: 16,
    ),
    CoreTeamMember(
      name: 'Adi Nath Bhawani',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-anb.jpg',
      year: 'Core Team',
      quote: '',
      order: 17,
    ),
    CoreTeamMember(
      name: 'Kushal Kishore',
      role: 'Sponsorship Co-Head',
      vertical: 'Sponsorship',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/spons-kk.jpg',
      year: 'Core Team',
      quote: '',
      order: 18,
    ),
    CoreTeamMember(
      name: 'Manas Gupta',
      role: 'Event Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-mg.jpg',
      year: 'Core Team',
      quote: '',
      order: 19,
    ),
    CoreTeamMember(
      name: 'Gopisetty Harsha Vardhan Naidu',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-gsr.jpg',
      year: 'Core Team',
      quote: '',
      order: 20,
    ),
    CoreTeamMember(
      name: 'Gurtej Singh',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-gt.jpg',
      year: 'Core Team',
      quote: '',
      order: 21,
    ),
    CoreTeamMember(
      name: 'Shreyashkar Singh',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-ss.jpg',
      year: 'Core Team',
      quote: '',
      order: 22,
    ),
    CoreTeamMember(
      name: 'Medithi Sujith',
      role: 'Event Management Co-Head',
      vertical: 'Event Management',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/event-sm.jpg',
      year: 'Core Team',
      quote: '',
      order: 23,
    ),
    CoreTeamMember(
      name: 'Manuwada Adithya',
      role: 'Public Relation Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pr.jpeg',
      year: 'Core Team',
      quote: '',
      order: 24,
    ),
    CoreTeamMember(
      name: 'Shivendu Shekhar',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-ss.jpg',
      year: 'Core Team',
      quote: '',
      order: 25,
    ),
    CoreTeamMember(
      name: 'Apoorv Krishna',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-ak.jpg',
      year: 'Core Team',
      quote: '',
      order: 26,
    ),
    CoreTeamMember(
      name: 'Daksh Mor',
      role: 'Public Relation Co-Head',
      vertical: 'Public Relation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/pub-dm.jpg',
      year: 'Core Team',
      quote: '',
      order: 27,
    ),
    CoreTeamMember(
      name: 'Pidathala Tanmayee',
      role: 'Design Team Head',
      vertical: 'Design',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/des-pt.jpg',
      year: 'Core Team',
      quote: '',
      order: 28,
    ),
    CoreTeamMember(
      name: 'Ramala Vivek',
      role: 'Design Team Co-Head',
      vertical: 'Design',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/des-rv.jpg',
      year: 'Core Team',
      quote: '',
      order: 29,
    ),
    CoreTeamMember(
      name: 'Shivam Verma',
      role: 'Operation And Logistics Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-sv.jpg',
      year: 'Core Team',
      quote: '',
      order: 30,
    ),
    CoreTeamMember(
      name: 'Chandragiri Praveen Kumar Reddy',
      role: 'Operation And Logistics Co-Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-cpkr.jpg',
      year: 'Core Team',
      quote: '',
      order: 31,
    ),
    CoreTeamMember(
      name: 'Siddhant Verma',
      role: 'Operation And Logistics Co-Head',
      vertical: 'Operation And Logistics',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/oal-sdv.jpg',
      year: 'Core Team',
      quote: '',
      order: 32,
    ),
    CoreTeamMember(
      name: 'Sucheta Ghosal',
      role: 'Web Development Head',
      vertical: 'Development',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/web-sg.jpg',
      year: 'Core Team',
      quote: '',
      order: 33,
    ),
    CoreTeamMember(
      name: 'Ayilamoni Shivani',
      role: 'App Development Head',
      vertical: 'Development',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/app-as.jpg',
      year: 'Core Team',
      quote: '',
      order: 34,
    ),
    CoreTeamMember(
      name: 'Charan Kondapalli',
      role: 'Security Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-ck.jpg',
      year: 'Core Team',
      quote: '',
      order: 35,
    ),
    CoreTeamMember(
      name: 'K Chaitanya',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-kc1.JPG',
      year: 'Core Team',
      quote: '',
      order: 36,
    ),
    CoreTeamMember(
      name: 'Shipal',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-ship.jpg',
      year: 'Core Team',
      quote: '',
      order: 37,
    ),
    CoreTeamMember(
      name: 'Eslavath Sheshank',
      role: 'Security Co-Head',
      vertical: 'Security',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/sec-es.jpg',
      year: 'Core Team',
      quote: '',
      order: 38,
    ),
    CoreTeamMember(
      name: 'Rohit Sunkara',
      role: 'Finance Head',
      vertical: 'Finance',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/fin-r.jpg',
      year: 'Core Team',
      quote: '',
      order: 39,
    ),
    CoreTeamMember(
      name: 'Sunka Varun Vashista',
      role: 'Finance Co-Head',
      vertical: 'Finance',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/fin-v.jpg',
      year: 'Core Team',
      quote: '',
      order: 40,
    ),
    CoreTeamMember(
      name: 'Tanishk Kumar Agrawal',
      role: 'Promotion Head',
      vertical: 'Promotion',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/prom-tka.jpg',
      year: 'Core Team',
      quote: '',
      order: 41,
    ),
    CoreTeamMember(
      name: 'Suyash Pandey',
      role: 'Promotion Co-Head',
      vertical: 'Promotion',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/prom-su.jpg',
      year: 'Core Team',
      quote: '',
      order: 42,
    ),
    CoreTeamMember(
      name: 'Keshav Mehnawat',
      role: 'Marketing Head',
      vertical: 'Marketing',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/keshav2.jpeg',
      year: 'Core Team',
      quote: '',
      order: 43,
    ),
    CoreTeamMember(
      name: 'Snehil Kashyap',
      role: 'Marketing Co-Head',
      vertical: 'Marketing',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/mark-sk.jpg',
      year: 'Core Team',
      quote: '',
      order: 44,
    ),
    CoreTeamMember(
      name: 'Mitta Sai Ramana Siddartha',
      role: 'Hospitality Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-sid.jpg',
      year: 'Core Team',
      quote: '',
      order: 45,
    ),
    CoreTeamMember(
      name: 'M Hema Suharshinii',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-hs.jpg',
      year: 'Core Team',
      quote: '',
      order: 46,
    ),
    CoreTeamMember(
      name: 'Keshav Jha',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-kj.jpg',
      year: 'Core Team',
      quote: '',
      order: 47,
    ),
    CoreTeamMember(
      name: 'Nidhi',
      role: 'Hospitality Co-Head',
      vertical: 'Hospitality',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/hosp-nidhi.jpg',
      year: 'Core Team',
      quote: '',
      order: 48,
    ),
    CoreTeamMember(
      name: 'Sreeja Peesa',
      role: 'Content And Documentation Head',
      vertical: 'Content And Documentation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/cad-sp.jpg',
      year: 'Core Team',
      quote: '',
      order: 49,
    ),
    CoreTeamMember(
      name: 'Rishabh Shukla',
      role: 'Content And Documentation Co-Head',
      vertical: 'Content And Documentation',
      phone: '',
      email: 'concetto@iitism.ac.in',
      imageUrl: 'assets/team/cad-rs.jpg',
      year: 'Core Team',
      quote: '',
      order: 50,
    ),
  ];

  static final List<AnnouncementItem> announcements = [
    AnnouncementItem(
      id: 'ann_1',
      title: "Welcome to CONCETTO '26 — Centenary Edition!",
      description:
          "IIT (ISM) Dhanbad proudly presents Concetto'26 with the theme \"Centauri Synapse — Forged Over a Century, Soaring Towards Infinity\". 39 official competitions and ₹ Lakhs in prizes await!",
      timestamp: DateTime(2026, 10, 1, 10, 0),
      tag: 'FEST',
    ),
    AnnouncementItem(
      id: 'ann_2',
      title: 'RoboWars & ChakraVyuh Arena Registrations Live',
      description:
          'Arena battle slots and maze navigation tracks are now open. Register your bots natively or via verified link before deadlines.',
      timestamp: DateTime(2026, 10, 2, 14, 30),
      tag: 'FLAGSHIP',
    ),
    AnnouncementItem(
      id: 'ann_3',
      title: 'Guest Lecture Series — Industry Leaders',
      description:
          'Special sessions with Indrajit Sanyal (Ericsson), Prasath P (HCLTech), and Varun G (Nokia) at Penman Auditorium on September 25, 2026.',
      timestamp: DateTime(2026, 10, 3, 11, 0),
      tag: 'CDC TALKS',
    ),
    AnnouncementItem(
      id: 'ann_4',
      title: 'MasterStack & CaseBlitz',
      description:
          'Overnight hackathon and premier business case study challenge portals are accepting team registrations.',
      timestamp: DateTime(2026, 10, 3, 18, 0),
      tag: 'HACKATHON',
    ),
    AnnouncementItem(
      id: 'ann_5',
      title: 'Fest Dates & Daily Schedule Confirmed',
      description:
          "Concetto'26 runs from October 08 to October 11, 2026 across IIT (ISM) Dhanbad campus. Access the Schedule tab for timeline and venues!",
      timestamp: DateTime(2026, 10, 4, 9, 0),
      tag: 'SCHEDULE',
    ),
  ];
}
